package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Tuesday, January 30, 2018 12:12:35 AM BDT
*/

public interface HelloOperations 
{
  String sayHello ();
  void getHello2 (HelloApp2.Hello2Holder hello2);
  void shutdown ();
} // interface HelloOperations
