package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Monday, February 5, 2018 2:06:40 PM BDT
*/

public interface HelloOperations 
{
  String sayHello ();
  void getHello2 (int how_many, HelloApp.Hello2ListHolder hello2List, HelloApp.SampleIteratorHolder iterator);
  void shutdown ();
} // interface HelloOperations
