package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Monday, January 29, 2018 11:48:31 AM BDT
*/

public interface HelloOperations 
{
  String sayHello();
  HelloApp.TestEnum getEnum();
  HelloApp.TestStruct getStruct(HelloApp.TestStructHolder testStruct);
  void shutdown();
} // interface HelloOperations
