package HelloApp;


/**
* HelloApp/Hello2ListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Monday, February 5, 2018 2:06:40 PM BDT
*/

public final class Hello2ListHolder implements org.omg.CORBA.portable.Streamable
{
  public HelloApp2.Hello2 value[] = null;

  public Hello2ListHolder ()
  {
  }

  public Hello2ListHolder (HelloApp2.Hello2[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HelloApp.Hello2ListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HelloApp.Hello2ListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HelloApp.Hello2ListHelper.type ();
  }

}
