package HelloApp;


/**
* HelloApp/SampleIteratorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Monday, February 5, 2018 2:06:40 PM BDT
*/

public interface SampleIteratorOperations 
{
  boolean next_n (int how_many, HelloApp.Hello2ListHolder meList);
  int getLength ();
  void destroy ();
} // interface SampleIteratorOperations
