package HelloApp;

/**
* HelloApp/SampleIteratorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Monday, February 5, 2018 2:06:40 PM BDT
*/

public final class SampleIteratorHolder implements org.omg.CORBA.portable.Streamable
{
  public HelloApp.SampleIterator value = null;

  public SampleIteratorHolder ()
  {
  }

  public SampleIteratorHolder (HelloApp.SampleIterator initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HelloApp.SampleIteratorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HelloApp.SampleIteratorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HelloApp.SampleIteratorHelper.type ();
  }

}
