package HelloApp;


/**
* HelloApp/SampleIteratorPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Monday, February 5, 2018 2:06:40 PM BDT
*/

public abstract class SampleIteratorPOA extends org.omg.PortableServer.Servant
 implements HelloApp.SampleIteratorOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("next_n", new java.lang.Integer (0));
    _methods.put ("getLength", new java.lang.Integer (1));
    _methods.put ("destroy", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // HelloApp/SampleIterator/next_n
       {
         int how_many = in.read_ulong ();
         HelloApp.Hello2ListHolder meList = new HelloApp.Hello2ListHolder ();
         boolean $result = false;
         $result = this.next_n (how_many, meList);
         out = $rh.createReply();
         out.write_boolean ($result);
         HelloApp.Hello2ListHelper.write (out, meList.value);
         break;
       }

       case 1:  // HelloApp/SampleIterator/getLength
       {
         int $result = (int)0;
         $result = this.getLength ();
         out = $rh.createReply();
         out.write_ulong ($result);
         break;
       }

       case 2:  // HelloApp/SampleIterator/destroy
       {
         this.destroy ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:HelloApp/SampleIterator:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public SampleIterator _this() 
  {
    return SampleIteratorHelper.narrow(
    super._this_object());
  }

  public SampleIterator _this(org.omg.CORBA.ORB orb) 
  {
    return SampleIteratorHelper.narrow(
    super._this_object(orb));
  }


} // class SampleIteratorPOA
