package HelloApp;


/**
* HelloApp/TestStruct.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Monday, January 29, 2018 11:48:31 AM BDT
*/

public final class TestStruct implements org.omg.CORBA.portable.IDLEntity
{
  public int intValue = (int)0;

  public TestStruct ()
  {
  } // ctor

  public TestStruct (int _intValue)
  {
    intValue = _intValue;
  } // ctor

} // class TestStruct
