package HelloApp;


/**
* HelloApp/TestEnum.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Monday, January 29, 2018 11:48:31 AM BDT
*/

public class TestEnum implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static HelloApp.TestEnum[] __array = new HelloApp.TestEnum [__size];

  public static final int _ONE = 0;
  public static final HelloApp.TestEnum ONE = new HelloApp.TestEnum(_ONE);
  public static final int _TWO = 1;
  public static final HelloApp.TestEnum TWO = new HelloApp.TestEnum(_TWO);

  public int value ()
  {
    return __value;
  }

  public static HelloApp.TestEnum from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected TestEnum (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class TestEnum
