package HelloApp;

/**
* HelloApp/TestStructHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Monday, January 29, 2018 11:48:31 AM BDT
*/

public final class TestStructHolder implements org.omg.CORBA.portable.Streamable
{
  public HelloApp.TestStruct value = null;

  public TestStructHolder ()
  {
  }

  public TestStructHolder (HelloApp.TestStruct initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HelloApp.TestStructHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HelloApp.TestStructHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HelloApp.TestStructHelper.type ();
  }

}
