module HelloApp
{
enum TestEnum
   {
    ONE,
    TWO
   };
   struct TestStruct
      {
       long intValue;
      };
  interface Hello
  {
  string sayHello();
  TestEnum getEnum();
  TestStruct getStruct(inout TestStruct testStruct);
  oneway void shutdown();

  };
};
