package CosNotifyFilter;


/**
* CosNotifyFilter/CallbackNotFound.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyFilter.idl
* Thursday, February 1, 2018 2:55:12 PM BDT
*/

public final class CallbackNotFound extends org.omg.CORBA.UserException
{

  public CallbackNotFound ()
  {
    super(CallbackNotFoundHelper.id());
  } // ctor


  public CallbackNotFound (String $reason)
  {
    super(CallbackNotFoundHelper.id() + "  " + $reason);
  } // ctor

} // class CallbackNotFound
