package CosNotifyFilter;

/**
* CosNotifyFilter/CallbackNotFoundHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyFilter.idl
* Thursday, February 1, 2018 2:55:12 PM BDT
*/

public final class CallbackNotFoundHolder implements org.omg.CORBA.portable.Streamable
{
  public CosNotifyFilter.CallbackNotFound value = null;

  public CallbackNotFoundHolder ()
  {
  }

  public CallbackNotFoundHolder (CosNotifyFilter.CallbackNotFound initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosNotifyFilter.CallbackNotFoundHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosNotifyFilter.CallbackNotFoundHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosNotifyFilter.CallbackNotFoundHelper.type ();
  }

}
