package CosNotifyFilter;


/**
* CosNotifyFilter/ConstraintNotFound.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyFilter.idl
* Thursday, February 1, 2018 2:55:12 PM BDT
*/

public final class ConstraintNotFound extends org.omg.CORBA.UserException
{
  public int id = (int)0;

  public ConstraintNotFound ()
  {
    super(ConstraintNotFoundHelper.id());
  } // ctor

  public ConstraintNotFound (int _id)
  {
    super(ConstraintNotFoundHelper.id());
    id = _id;
  } // ctor


  public ConstraintNotFound (String $reason, int _id)
  {
    super(ConstraintNotFoundHelper.id() + "  " + $reason);
    id = _id;
  } // ctor

} // class ConstraintNotFound
