package CosNotifyFilter;

/**
* CosNotifyFilter/DuplicateConstraintIDHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyFilter.idl
* Thursday, February 1, 2018 2:55:12 PM BDT
*/


/**
    * Exception used to indicate a duplicate constraint ID.
    */
public final class DuplicateConstraintIDHolder implements org.omg.CORBA.portable.Streamable
{
  public CosNotifyFilter.DuplicateConstraintID value = null;

  public DuplicateConstraintIDHolder ()
  {
  }

  public DuplicateConstraintIDHolder (CosNotifyFilter.DuplicateConstraintID initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosNotifyFilter.DuplicateConstraintIDHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosNotifyFilter.DuplicateConstraintIDHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosNotifyFilter.DuplicateConstraintIDHelper.type ();
  }

}
