package CosNotifyFilter;


/**
* CosNotifyFilter/FilterFactory.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyFilter.idl
* Thursday, February 1, 2018 2:55:13 PM BDT
*/


/**
    * Interface for a filter factory.
    */
public interface FilterFactory extends FilterFactoryOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FilterFactory
