package CosNotifyFilter;


/**
* CosNotifyFilter/FilterIDSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyFilter.idl
* Thursday, February 1, 2018 2:55:13 PM BDT
*/


/**
    * A sequence of FilterID.
    */
public final class FilterIDSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public FilterIDSeqHolder ()
  {
  }

  public FilterIDSeqHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosNotifyFilter.FilterIDSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosNotifyFilter.FilterIDSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosNotifyFilter.FilterIDSeqHelper.type ();
  }

}
