package CosNotifyFilter;

/**
* CosNotifyFilter/FilterAdminHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyFilter.idl
* Thursday, February 1, 2018 2:55:13 PM BDT
*/


/**
    * Interface for filter administrators.
    */
public final class FilterAdminHolder implements org.omg.CORBA.portable.Streamable
{
  public CosNotifyFilter.FilterAdmin value = null;

  public FilterAdminHolder ()
  {
  }

  public FilterAdminHolder (CosNotifyFilter.FilterAdmin initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosNotifyFilter.FilterAdminHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosNotifyFilter.FilterAdminHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosNotifyFilter.FilterAdminHelper.type ();
  }

}
