package CosNotifyFilter;

/**
* CosNotifyFilter/FilterNotFoundHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyFilter.idl
* Thursday, February 1, 2018 2:55:13 PM BDT
*/

public final class FilterNotFoundHolder implements org.omg.CORBA.portable.Streamable
{
  public CosNotifyFilter.FilterNotFound value = null;

  public FilterNotFoundHolder ()
  {
  }

  public FilterNotFoundHolder (CosNotifyFilter.FilterNotFound initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosNotifyFilter.FilterNotFoundHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosNotifyFilter.FilterNotFoundHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosNotifyFilter.FilterNotFoundHelper.type ();
  }

}
