package CosNotifyFilter;


/**
* CosNotifyFilter/FilterNotFound.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyFilter.idl
* Thursday, February 1, 2018 2:55:13 PM BDT
*/

public final class FilterNotFound extends org.omg.CORBA.UserException
{

  public FilterNotFound ()
  {
    super(FilterNotFoundHelper.id());
  } // ctor


  public FilterNotFound (String $reason)
  {
    super(FilterNotFoundHelper.id() + "  " + $reason);
  } // ctor

} // class FilterNotFound
