package CosNotifyFilter;


/**
* CosNotifyFilter/FilterAdminOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyFilter.idl
* Thursday, February 1, 2018 2:55:13 PM BDT
*/


/**
    * Interface for filter administrators.
    */
public interface FilterAdminOperations 
{

  /**
         * Add a filter to this object's list of filters. All these filters
         * are tried upon reception of an event.
         * @parm <code>new_filter</code> - The filter to add.
         * @returns An unique ID that identifies the added filter.
         */
  int add_filter (CosNotifyFilter.Filter new_filter);

  /**
         * Remove a filter from this object's list of filters.
         * @parm <code>filter</code> - The filter ID.
         * @raises FilterNotFound If the ID does not correspond to any
         * filter that has been added to this object.
         */
  void remove_filter (int filter) throws CosNotifyFilter.FilterNotFound;

  /**
         * Get a filter from the filter ID.
         * @parm <code>filter</code> - The filter ID.
         * @raises FilterNotFound If the ID does not correspond to any
         * filter that has been added to this object.
         */
  CosNotifyFilter.Filter get_filter (int filter) throws CosNotifyFilter.FilterNotFound;

  /**
         * Get all filters added to this administration object.
         * @returns A sequence of filter IDs.
         */
  int[] get_all_filters ();

  /**
         * Remove all filters added to this administration object.
         */
  void remove_all_filters ();
} // interface FilterAdminOperations
