package CosNotifyFilter;


/**
* CosNotifyFilter/FilterAdmin.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyFilter.idl
* Thursday, February 1, 2018 2:55:13 PM BDT
*/


/**
    * Interface for filter administrators.
    */
public interface FilterAdmin extends FilterAdminOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FilterAdmin
