package CosNotifyFilter;


/**
* CosNotifyFilter/InvalidGrammar.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyFilter.idl
* Thursday, February 1, 2018 2:55:12 PM BDT
*/

public final class InvalidGrammar extends org.omg.CORBA.UserException
{

  public InvalidGrammar ()
  {
    super(InvalidGrammarHelper.id());
  } // ctor


  public InvalidGrammar (String $reason)
  {
    super(InvalidGrammarHelper.id() + "  " + $reason);
  } // ctor

} // class InvalidGrammar
