package CosNotifyFilter;


/**
* CosNotifyFilter/InvalidValue.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyFilter.idl
* Thursday, February 1, 2018 2:55:12 PM BDT
*/

public final class InvalidValue extends org.omg.CORBA.UserException
{
  public CosNotifyFilter.ConstraintExp constr = null;
  public org.omg.CORBA.Any value = null;

  public InvalidValue ()
  {
    super(InvalidValueHelper.id());
  } // ctor

  public InvalidValue (CosNotifyFilter.ConstraintExp _constr, org.omg.CORBA.Any _value)
  {
    super(InvalidValueHelper.id());
    constr = _constr;
    value = _value;
  } // ctor


  public InvalidValue (String $reason, CosNotifyFilter.ConstraintExp _constr, org.omg.CORBA.Any _value)
  {
    super(InvalidValueHelper.id() + "  " + $reason);
    constr = _constr;
    value = _value;
  } // ctor

} // class InvalidValue
