package CosNotifyFilter;

/**
* CosNotifyFilter/InvalidGrammarHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyFilter.idl
* Thursday, February 1, 2018 2:55:12 PM BDT
*/

public final class InvalidGrammarHolder implements org.omg.CORBA.portable.Streamable
{
  public CosNotifyFilter.InvalidGrammar value = null;

  public InvalidGrammarHolder ()
  {
  }

  public InvalidGrammarHolder (CosNotifyFilter.InvalidGrammar initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosNotifyFilter.InvalidGrammarHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosNotifyFilter.InvalidGrammarHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosNotifyFilter.InvalidGrammarHelper.type ();
  }

}
