package CosNotifyFilter;


/**
* CosNotifyFilter/UnsupportedFilterableData.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyFilter.idl
* Thursday, February 1, 2018 2:55:12 PM BDT
*/

public final class UnsupportedFilterableData extends org.omg.CORBA.UserException
{

  public UnsupportedFilterableData ()
  {
    super(UnsupportedFilterableDataHelper.id());
  } // ctor


  public UnsupportedFilterableData (String $reason)
  {
    super(UnsupportedFilterableDataHelper.id() + "  " + $reason);
  } // ctor

} // class UnsupportedFilterableData
