package CosTrading.LinkPackage;

/**
* CosTrading/LinkPackage/DefaultFollowTooPermissiveHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:15 PM BDT
*/

public final class DefaultFollowTooPermissiveHolder implements org.omg.CORBA.portable.Streamable
{
  public CosTrading.LinkPackage.DefaultFollowTooPermissive value = null;

  public DefaultFollowTooPermissiveHolder ()
  {
  }

  public DefaultFollowTooPermissiveHolder (CosTrading.LinkPackage.DefaultFollowTooPermissive initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosTrading.LinkPackage.DefaultFollowTooPermissiveHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosTrading.LinkPackage.DefaultFollowTooPermissiveHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosTrading.LinkPackage.DefaultFollowTooPermissiveHelper.type ();
  }

}
