package CosTrading.LinkPackage;

/**
* CosTrading/LinkPackage/DuplicateLinkNameHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:15 PM BDT
*/

public final class DuplicateLinkNameHolder implements org.omg.CORBA.portable.Streamable
{
  public CosTrading.LinkPackage.DuplicateLinkName value = null;

  public DuplicateLinkNameHolder ()
  {
  }

  public DuplicateLinkNameHolder (CosTrading.LinkPackage.DuplicateLinkName initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosTrading.LinkPackage.DuplicateLinkNameHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosTrading.LinkPackage.DuplicateLinkNameHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosTrading.LinkPackage.DuplicateLinkNameHelper.type ();
  }

}
