package CosTrading.LinkPackage;


/**
* CosTrading/LinkPackage/DuplicateLinkName.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:15 PM BDT
*/

public final class DuplicateLinkName extends org.omg.CORBA.UserException
{
  public String name = null;

  public DuplicateLinkName ()
  {
    super(DuplicateLinkNameHelper.id());
  } // ctor

  public DuplicateLinkName (String _name)
  {
    super(DuplicateLinkNameHelper.id());
    name = _name;
  } // ctor


  public DuplicateLinkName (String $reason, String _name)
  {
    super(DuplicateLinkNameHelper.id() + "  " + $reason);
    name = _name;
  } // ctor

} // class DuplicateLinkName
