package CosTrading.LinkPackage;


/**
* CosTrading/LinkPackage/IllegalLinkName.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:15 PM BDT
*/

public final class IllegalLinkName extends org.omg.CORBA.UserException
{
  public String name = null;

  public IllegalLinkName ()
  {
    super(IllegalLinkNameHelper.id());
  } // ctor

  public IllegalLinkName (String _name)
  {
    super(IllegalLinkNameHelper.id());
    name = _name;
  } // ctor


  public IllegalLinkName (String $reason, String _name)
  {
    super(IllegalLinkNameHelper.id() + "  " + $reason);
    name = _name;
  } // ctor

} // class IllegalLinkName
