package CosTrading.LinkPackage;

/**
* CosTrading/LinkPackage/LimitingFollowTooPermissiveHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:15 PM BDT
*/

public final class LimitingFollowTooPermissiveHolder implements org.omg.CORBA.portable.Streamable
{
  public CosTrading.LinkPackage.LimitingFollowTooPermissive value = null;

  public LimitingFollowTooPermissiveHolder ()
  {
  }

  public LimitingFollowTooPermissiveHolder (CosTrading.LinkPackage.LimitingFollowTooPermissive initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosTrading.LinkPackage.LimitingFollowTooPermissiveHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosTrading.LinkPackage.LimitingFollowTooPermissiveHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosTrading.LinkPackage.LimitingFollowTooPermissiveHelper.type ();
  }

}
