package CosTrading.LinkPackage;


/**
* CosTrading/LinkPackage/UnknownLinkName.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:15 PM BDT
*/

public final class UnknownLinkName extends org.omg.CORBA.UserException
{
  public String name = null;

  public UnknownLinkName ()
  {
    super(UnknownLinkNameHelper.id());
  } // ctor

  public UnknownLinkName (String _name)
  {
    super(UnknownLinkNameHelper.id());
    name = _name;
  } // ctor


  public UnknownLinkName (String $reason, String _name)
  {
    super(UnknownLinkNameHelper.id() + "  " + $reason);
    name = _name;
  } // ctor

} // class UnknownLinkName
