package CosTrading.RegisterPackage;


/**
* CosTrading/RegisterPackage/IllegalTraderName.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:14 PM BDT
*/

public final class IllegalTraderName extends org.omg.CORBA.UserException
{
  public String name[] = null;

  public IllegalTraderName ()
  {
    super(IllegalTraderNameHelper.id());
  } // ctor

  public IllegalTraderName (String[] _name)
  {
    super(IllegalTraderNameHelper.id());
    name = _name;
  } // ctor


  public IllegalTraderName (String $reason, String[] _name)
  {
    super(IllegalTraderNameHelper.id() + "  " + $reason);
    name = _name;
  } // ctor

} // class IllegalTraderName
