package CosTrading.RegisterPackage;

/**
* CosTrading/RegisterPackage/InterfaceTypeMismatchHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:14 PM BDT
*/

public final class InterfaceTypeMismatchHolder implements org.omg.CORBA.portable.Streamable
{
  public CosTrading.RegisterPackage.InterfaceTypeMismatch value = null;

  public InterfaceTypeMismatchHolder ()
  {
  }

  public InterfaceTypeMismatchHolder (CosTrading.RegisterPackage.InterfaceTypeMismatch initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosTrading.RegisterPackage.InterfaceTypeMismatchHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosTrading.RegisterPackage.InterfaceTypeMismatchHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosTrading.RegisterPackage.InterfaceTypeMismatchHelper.type ();
  }

}
