package CosTrading.RegisterPackage;


/**
* CosTrading/RegisterPackage/InterfaceTypeMismatch.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:14 PM BDT
*/

public final class InterfaceTypeMismatch extends org.omg.CORBA.UserException
{
  public String type = null;
  public org.omg.CORBA.Object reference = null;

  public InterfaceTypeMismatch ()
  {
    super(InterfaceTypeMismatchHelper.id());
  } // ctor

  public InterfaceTypeMismatch (String _type, org.omg.CORBA.Object _reference)
  {
    super(InterfaceTypeMismatchHelper.id());
    type = _type;
    reference = _reference;
  } // ctor


  public InterfaceTypeMismatch (String $reason, String _type, org.omg.CORBA.Object _reference)
  {
    super(InterfaceTypeMismatchHelper.id() + "  " + $reason);
    type = _type;
    reference = _reference;
  } // ctor

} // class InterfaceTypeMismatch
