package CosTrading.RegisterPackage;

/**
* CosTrading/RegisterPackage/InvalidObjectRefHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:14 PM BDT
*/

public final class InvalidObjectRefHolder implements org.omg.CORBA.portable.Streamable
{
  public CosTrading.RegisterPackage.InvalidObjectRef value = null;

  public InvalidObjectRefHolder ()
  {
  }

  public InvalidObjectRefHolder (CosTrading.RegisterPackage.InvalidObjectRef initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosTrading.RegisterPackage.InvalidObjectRefHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosTrading.RegisterPackage.InvalidObjectRefHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosTrading.RegisterPackage.InvalidObjectRefHelper.type ();
  }

}
