package CosTrading.RegisterPackage;


/**
* CosTrading/RegisterPackage/InvalidObjectRef.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:14 PM BDT
*/

public final class InvalidObjectRef extends org.omg.CORBA.UserException
{
  public org.omg.CORBA.Object ref = null;

  public InvalidObjectRef ()
  {
    super(InvalidObjectRefHelper.id());
  } // ctor

  public InvalidObjectRef (org.omg.CORBA.Object _ref)
  {
    super(InvalidObjectRefHelper.id());
    ref = _ref;
  } // ctor


  public InvalidObjectRef (String $reason, org.omg.CORBA.Object _ref)
  {
    super(InvalidObjectRefHelper.id() + "  " + $reason);
    ref = _ref;
  } // ctor

} // class InvalidObjectRef
