package CosTrading.RegisterPackage;


/**
* CosTrading/RegisterPackage/MandatoryProperty.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:14 PM BDT
*/

public final class MandatoryProperty extends org.omg.CORBA.UserException
{
  public String type = null;
  public String name = null;

  public MandatoryProperty ()
  {
    super(MandatoryPropertyHelper.id());
  } // ctor

  public MandatoryProperty (String _type, String _name)
  {
    super(MandatoryPropertyHelper.id());
    type = _type;
    name = _name;
  } // ctor


  public MandatoryProperty (String $reason, String _type, String _name)
  {
    super(MandatoryPropertyHelper.id() + "  " + $reason);
    type = _type;
    name = _name;
  } // ctor

} // class MandatoryProperty
