package CosTrading.RegisterPackage;


/**
* CosTrading/RegisterPackage/OfferInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:15 PM BDT
*/

public final class OfferInfo implements org.omg.CORBA.portable.IDLEntity
{
  public org.omg.CORBA.Object reference = null;
  public String type = null;
  public CosTrading.Property properties[] = null;

  public OfferInfo ()
  {
  } // ctor

  public OfferInfo (org.omg.CORBA.Object _reference, String _type, CosTrading.Property[] _properties)
  {
    reference = _reference;
    type = _type;
    properties = _properties;
  } // ctor

} // class OfferInfo
