package CosTrading.RegisterPackage;

/**
* CosTrading/RegisterPackage/ProxyOfferIdHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:14 PM BDT
*/

public final class ProxyOfferIdHolder implements org.omg.CORBA.portable.Streamable
{
  public CosTrading.RegisterPackage.ProxyOfferId value = null;

  public ProxyOfferIdHolder ()
  {
  }

  public ProxyOfferIdHolder (CosTrading.RegisterPackage.ProxyOfferId initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosTrading.RegisterPackage.ProxyOfferIdHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosTrading.RegisterPackage.ProxyOfferIdHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosTrading.RegisterPackage.ProxyOfferIdHelper.type ();
  }

}
