package CosTrading.RegisterPackage;


/**
* CosTrading/RegisterPackage/ProxyOfferId.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:14 PM BDT
*/

public final class ProxyOfferId extends org.omg.CORBA.UserException
{
  public String id = null;

  public ProxyOfferId ()
  {
    super(ProxyOfferIdHelper.id());
  } // ctor

  public ProxyOfferId (String _id)
  {
    super(ProxyOfferIdHelper.id());
    id = _id;
  } // ctor


  public ProxyOfferId (String $reason, String _id)
  {
    super(ProxyOfferIdHelper.id() + "  " + $reason);
    id = _id;
  } // ctor

} // class ProxyOfferId
