package CosTrading.RegisterPackage;


/**
* CosTrading/RegisterPackage/RegisterNotSupported.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:14 PM BDT
*/

public final class RegisterNotSupported extends org.omg.CORBA.UserException
{
  public String name[] = null;

  public RegisterNotSupported ()
  {
    super(RegisterNotSupportedHelper.id());
  } // ctor

  public RegisterNotSupported (String[] _name)
  {
    super(RegisterNotSupportedHelper.id());
    name = _name;
  } // ctor


  public RegisterNotSupported (String $reason, String[] _name)
  {
    super(RegisterNotSupportedHelper.id() + "  " + $reason);
    name = _name;
  } // ctor

} // class RegisterNotSupported
