package CosTrading.RegisterPackage;


/**
* CosTrading/RegisterPackage/UnknownTraderName.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:14 PM BDT
*/

public final class UnknownTraderName extends org.omg.CORBA.UserException
{
  public String name[] = null;

  public UnknownTraderName ()
  {
    super(UnknownTraderNameHelper.id());
  } // ctor

  public UnknownTraderName (String[] _name)
  {
    super(UnknownTraderNameHelper.id());
    name = _name;
  } // ctor


  public UnknownTraderName (String $reason, String[] _name)
  {
    super(UnknownTraderNameHelper.id() + "  " + $reason);
    name = _name;
  } // ctor

} // class UnknownTraderName
