package CosTrading.AdminPackage;


/**
* CosTrading/AdminPackage/OctetSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:15 PM BDT
*/

public final class OctetSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public byte value[] = null;

  public OctetSeqHolder ()
  {
  }

  public OctetSeqHolder (byte[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosTrading.AdminPackage.OctetSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosTrading.AdminPackage.OctetSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosTrading.AdminPackage.OctetSeqHelper.type ();
  }

}
