package HelloApp2;


/**
* HelloApp2/Hello2.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello2.idl
* Tuesday, January 30, 2018 12:12:51 AM BDT
*/

public interface Hello2 extends Hello2Operations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello2
