package HelloApp2;


/**
* HelloApp2/Hello2Helper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello2.idl
* Monday, February 5, 2018 1:31:05 PM BDT
*/

abstract public class Hello2Helper
{
  private static String  _id = "IDL:HelloApp2/Hello2:1.0";

  public static void insert (org.omg.CORBA.Any a, HelloApp2.Hello2 that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static HelloApp2.Hello2 extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [1];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "id",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (HelloApp2.Hello2Helper.id (), "Hello2", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static HelloApp2.Hello2 read (org.omg.CORBA.portable.InputStream istream)
  {
    HelloApp2.Hello2 value = new HelloApp2.Hello2 ();
    value.id = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, HelloApp2.Hello2 value)
  {
    ostream.write_string (value.id);
  }

}
