package HelloApp2;

/**
* HelloApp2/Hello2Holder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello2.idl
* Monday, February 5, 2018 1:31:05 PM BDT
*/

public final class Hello2Holder implements org.omg.CORBA.portable.Streamable
{
  public HelloApp2.Hello2 value = null;

  public Hello2Holder ()
  {
  }

  public Hello2Holder (HelloApp2.Hello2 initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HelloApp2.Hello2Helper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HelloApp2.Hello2Helper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HelloApp2.Hello2Helper.type ();
  }

}
