package HelloApp2;


/**
* HelloApp2/Hello2.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello2.idl
* Monday, February 5, 2018 1:31:05 PM BDT
*/

public final class Hello2 implements org.omg.CORBA.portable.IDLEntity
{
  public String id = null;

  public Hello2 ()
  {
  } // ctor

  public Hello2 (String _id)
  {
    id = _id;
  } // ctor

} // class Hello2
