package HelloApp2;


/**
* HelloApp2/Hello2Operations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello2.idl
* Tuesday, January 30, 2018 12:12:51 AM BDT
*/

public interface Hello2Operations 
{
  String sayHello2 ();
} // interface Hello2Operations
