package CosNaming;


/**
* CosNaming/BindingIteratorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNaming.idl
* Thursday, February 1, 2018 2:55:07 PM BDT
*/


/**
 * The BindingIterator interface allows a client to iterate through the
 * bindings using the next_one or next_n operations.
 */
public interface BindingIteratorOperations 
{

  /**
 * This operation returns the next binding. If there are no more
 * bindings, false is returned.
 *
 * @parm b - next binding.
 */
  boolean next_one (CosNaming.BindingHolder b);

  /** 
 * This operation returns at most the requested number of bindings.
 *
 * @parm how_many - maximum number of binding to return in bl.
 * @parm bl - list of bindings.
 */
  boolean next_n (int how_many, CosNaming.BindingListHolder bl);

  /** 
 * This operation destroys the iterator.
 */
  void destroy ();
} // interface BindingIteratorOperations
