package CosTrading.LookupPackage;

/**
* CosTrading/LookupPackage/IllegalPolicyNameHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:14 PM BDT
*/

public final class IllegalPolicyNameHolder implements org.omg.CORBA.portable.Streamable
{
  public CosTrading.LookupPackage.IllegalPolicyName value = null;

  public IllegalPolicyNameHolder ()
  {
  }

  public IllegalPolicyNameHolder (CosTrading.LookupPackage.IllegalPolicyName initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosTrading.LookupPackage.IllegalPolicyNameHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosTrading.LookupPackage.IllegalPolicyNameHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosTrading.LookupPackage.IllegalPolicyNameHelper.type ();
  }

}
