package CosTrading.LookupPackage;

/**
* CosTrading/LookupPackage/IllegalPreferenceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:14 PM BDT
*/

public final class IllegalPreferenceHolder implements org.omg.CORBA.portable.Streamable
{
  public CosTrading.LookupPackage.IllegalPreference value = null;

  public IllegalPreferenceHolder ()
  {
  }

  public IllegalPreferenceHolder (CosTrading.LookupPackage.IllegalPreference initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosTrading.LookupPackage.IllegalPreferenceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosTrading.LookupPackage.IllegalPreferenceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosTrading.LookupPackage.IllegalPreferenceHelper.type ();
  }

}
