package CosTrading.LookupPackage;


/**
* CosTrading/LookupPackage/InvalidPolicyValue.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:14 PM BDT
*/

public final class InvalidPolicyValue extends org.omg.CORBA.UserException
{
  public CosTrading.Policy the_policy = null;

  public InvalidPolicyValue ()
  {
    super(InvalidPolicyValueHelper.id());
  } // ctor

  public InvalidPolicyValue (CosTrading.Policy _the_policy)
  {
    super(InvalidPolicyValueHelper.id());
    the_policy = _the_policy;
  } // ctor


  public InvalidPolicyValue (String $reason, CosTrading.Policy _the_policy)
  {
    super(InvalidPolicyValueHelper.id() + "  " + $reason);
    the_policy = _the_policy;
  } // ctor

} // class InvalidPolicyValue
