package CosTrading.LookupPackage;

/**
* CosTrading/LookupPackage/InvalidPolicyValueHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:14 PM BDT
*/

public final class InvalidPolicyValueHolder implements org.omg.CORBA.portable.Streamable
{
  public CosTrading.LookupPackage.InvalidPolicyValue value = null;

  public InvalidPolicyValueHolder ()
  {
  }

  public InvalidPolicyValueHolder (CosTrading.LookupPackage.InvalidPolicyValue initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosTrading.LookupPackage.InvalidPolicyValueHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosTrading.LookupPackage.InvalidPolicyValueHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosTrading.LookupPackage.InvalidPolicyValueHelper.type ();
  }

}
