package CosEventComm;


/**
* CosEventComm/PullConsumerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosEventComm.idl
* Thursday, February 1, 2018 2:55:06 PM BDT
*/


/**
    * Interface for a pull consumer.
    */
public interface PullConsumerOperations 
{

  /**
       * Disconnect a pull consumer.
       */
  void disconnect_pull_consumer ();
} // interface PullConsumerOperations
