package CosEventComm;


/**
* CosEventComm/PullSupplier.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosEventComm.idl
* Thursday, February 1, 2018 2:55:06 PM BDT
*/


/**
    * Interface for a pull supplier.
    */
public interface PullSupplier extends PullSupplierOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PullSupplier
