package CosEventComm;


/**
* CosEventComm/PushConsumer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosEventComm.idl
* Thursday, February 1, 2018 2:55:06 PM BDT
*/


/**
    * Interface for a push consumer.
    */
public interface PushConsumer extends PushConsumerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PushConsumer
