package CosEventComm;


/**
* CosEventComm/PushSupplierOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosEventComm.idl
* Thursday, February 1, 2018 2:55:06 PM BDT
*/


/**
    * Interface for a push supplier.
    */
public interface PushSupplierOperations 
{

  /**
       * Disconnect a push supplier.
       */
  void disconnect_push_supplier ();
} // interface PushSupplierOperations
