package CosEventChannelAdmin;


/**
* CosEventChannelAdmin/EventChannelOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosEventChannelAdmin.idl
* Thursday, February 1, 2018 2:55:05 PM BDT
*/


/**
    * Interface for the event channel.
    */
public interface EventChannelOperations 
{

  /**
         * Gets an object reference to the administration object
         * for event consumers.
         * @returns The <code>ConsumerAdmin</code> object reference.
         */
  CosEventChannelAdmin.ConsumerAdmin for_consumers ();

  /**
         * Gets an object reference to the administration object
         * for event suppliers.
         * @returns The <code>SupplierAdmin</code> object reference.
         */
  CosEventChannelAdmin.SupplierAdmin for_suppliers ();

  /**
         * Destroys this event channel and released any storage used.
         */
  void destroy ();
} // interface EventChannelOperations
