package CosEventChannelAdmin;


/**
* CosEventChannelAdmin/EventChannel.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosEventChannelAdmin.idl
* Thursday, February 1, 2018 2:55:05 PM BDT
*/


/**
    * Interface for the event channel.
    */
public interface EventChannel extends EventChannelOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface EventChannel
