package CosEventChannelAdmin;


/**
* CosEventChannelAdmin/ProxyPullSupplier.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosEventChannelAdmin.idl
* Thursday, February 1, 2018 2:55:05 PM BDT
*/


/**
    * Interface for a proxy pull supplier.
    */
public interface ProxyPullSupplier extends ProxyPullSupplierOperations, CosEventComm.PullSupplier, org.omg.CORBA.portable.IDLEntity 
{
} // interface ProxyPullSupplier
