package CosEventChannelAdmin;


/**
* CosEventChannelAdmin/ProxyPullConsumer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosEventChannelAdmin.idl
* Thursday, February 1, 2018 2:55:05 PM BDT
*/


/**
    * Interface for a proxy pull consumer.
    */
public interface ProxyPullConsumer extends ProxyPullConsumerOperations, CosEventComm.PullConsumer, org.omg.CORBA.portable.IDLEntity 
{
} // interface ProxyPullConsumer
