package CosEventChannelAdmin;


/**
* CosEventChannelAdmin/ProxyPushSupplier.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosEventChannelAdmin.idl
* Thursday, February 1, 2018 2:55:05 PM BDT
*/


/**
    * Interface for a proxy push supplier.
    */
public interface ProxyPushSupplier extends ProxyPushSupplierOperations, CosEventComm.PushSupplier, org.omg.CORBA.portable.IDLEntity 
{
} // interface ProxyPushSupplier
