package CosEventChannelAdmin;


/**
* CosEventChannelAdmin/SupplierAdmin.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosEventChannelAdmin.idl
* Thursday, February 1, 2018 2:55:05 PM BDT
*/


/**
    * Interface for the supplier administration object.
    */
public interface SupplierAdmin extends SupplierAdminOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface SupplierAdmin
