package CosEventChannelAdmin;


/**
* CosEventChannelAdmin/SupplierAdminOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosEventChannelAdmin.idl
* Thursday, February 1, 2018 2:55:05 PM BDT
*/


/**
    * Interface for the supplier administration object.
    */
public interface SupplierAdminOperations 
{

  /**
         * Obtain a push consumer proxy for this administration object.
         * @returns A <code>ProxyPushConsumer</code> object reference.
         */
  CosEventChannelAdmin.ProxyPushConsumer obtain_push_consumer ();

  /**
         * Obtain a pull consumer proxy for this administration object.
         * @returns A <code>ProxyPullConsumer</code> object reference.
         */
  CosEventChannelAdmin.ProxyPullConsumer obtain_pull_consumer ();
} // interface SupplierAdminOperations
