package DsNotifyLogAdmin;


/**
* DsNotifyLogAdmin/NotifyLogOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsNotifyLogAdmin.idl
* Thursday, February 1, 2018 2:55:18 PM BDT
*/

public interface NotifyLogOperations  extends DsEventLogAdmin.EventLogOperations, CosNotifyChannelAdmin.EventChannelOperations
{
  CosNotifyFilter.Filter get_filter ();
  void set_filter (CosNotifyFilter.Filter filter);
} // interface NotifyLogOperations
