package DsNotifyLogAdmin;


/**
* DsNotifyLogAdmin/NotifyLog.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsNotifyLogAdmin.idl
* Thursday, February 1, 2018 2:55:18 PM BDT
*/

public interface NotifyLog extends NotifyLogOperations, DsEventLogAdmin.EventLog, CosNotifyChannelAdmin.EventChannel
{
} // interface NotifyLog
