package DsNotifyLogAdmin;

/**
* DsNotifyLogAdmin/NotifyLogFactoryHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsNotifyLogAdmin.idl
* Thursday, February 1, 2018 2:55:18 PM BDT
*/

public final class NotifyLogFactoryHolder implements org.omg.CORBA.portable.Streamable
{
  public DsNotifyLogAdmin.NotifyLogFactory value = null;

  public NotifyLogFactoryHolder ()
  {
  }

  public NotifyLogFactoryHolder (DsNotifyLogAdmin.NotifyLogFactory initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DsNotifyLogAdmin.NotifyLogFactoryHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DsNotifyLogAdmin.NotifyLogFactoryHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DsNotifyLogAdmin.NotifyLogFactoryHelper.type ();
  }

}
