package DsNotifyLogAdmin;

/**
* DsNotifyLogAdmin/NotifyLogHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsNotifyLogAdmin.idl
* Thursday, February 1, 2018 2:55:18 PM BDT
*/

public final class NotifyLogHolder implements org.omg.CORBA.portable.Streamable
{
  public DsNotifyLogAdmin.NotifyLog value = null;

  public NotifyLogHolder ()
  {
  }

  public NotifyLogHolder (DsNotifyLogAdmin.NotifyLog initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DsNotifyLogAdmin.NotifyLogHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DsNotifyLogAdmin.NotifyLogHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DsNotifyLogAdmin.NotifyLogHelper.type ();
  }

}
