package DsNotifyLogAdmin;


/**
* DsNotifyLogAdmin/NotifyLogFactoryOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsNotifyLogAdmin.idl
* Thursday, February 1, 2018 2:55:18 PM BDT
*/

public interface NotifyLogFactoryOperations  extends DsLogAdmin.LogMgrOperations, CosNotifyChannelAdmin.ConsumerAdminOperations
{
  DsNotifyLogAdmin.NotifyLog create (short full_action, long max_size, short[] thresholds, CosNotification.Property[] initial_qos, CosNotification.Property[] initial_admin, org.omg.CORBA.IntHolder id) throws DsLogAdmin.InvalidLogFullAction, DsLogAdmin.InvalidThreshold, CosNotification.UnsupportedQoS, CosNotification.UnsupportedAdmin;
  DsNotifyLogAdmin.NotifyLog create_with_id (int id, short full_action, long max_size, short[] thresholds, CosNotification.Property[] initial_qos, CosNotification.Property[] initial_admin) throws DsLogAdmin.LogIdAlreadyExists, DsLogAdmin.InvalidLogFullAction, DsLogAdmin.InvalidThreshold, CosNotification.UnsupportedQoS, CosNotification.UnsupportedAdmin;
} // interface NotifyLogFactoryOperations
