package CosNotification;


/**
* CosNotification/AdminPropertiesAdmin.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotification.idl
* Thursday, February 1, 2018 2:55:08 PM BDT
*/


/**
    * An interface for objects that have administrative settings.
    */
public interface AdminPropertiesAdmin extends AdminPropertiesAdminOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AdminPropertiesAdmin
