package CosNotification;


/**
* CosNotification/EventType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotification.idl
* Thursday, February 1, 2018 2:55:08 PM BDT
*/

public final class EventType implements org.omg.CORBA.portable.IDLEntity
{
  public String domain_name = null;
  public String type_name = null;

  public EventType ()
  {
  } // ctor

  public EventType (String _domain_name, String _type_name)
  {
    domain_name = _domain_name;
    type_name = _type_name;
  } // ctor

} // class EventType
