package CosNotification;


/**
* CosNotification/FixedEventHeader.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotification.idl
* Thursday, February 1, 2018 2:55:08 PM BDT
*/

public final class FixedEventHeader implements org.omg.CORBA.portable.IDLEntity
{
  public CosNotification.EventType event_type = null;
  public String event_name = null;

  public FixedEventHeader ()
  {
  } // ctor

  public FixedEventHeader (CosNotification.EventType _event_type, String _event_name)
  {
    event_type = _event_type;
    event_name = _event_name;
  } // ctor

} // class FixedEventHeader
