package CosNotification;


/**
* CosNotification/LifoOrder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotification.idl
* Thursday, February 1, 2018 2:55:08 PM BDT
*/

public interface LifoOrder
{

  // DiscardPolicy takes on the same values as OrderPolicy, plus
  public static final short value = (short)(4);
}
