package CosNotification;


/**
* CosNotification/MaxQueueLength.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotification.idl
* Thursday, February 1, 2018 2:55:08 PM BDT
*/

public interface MaxQueueLength
{

  // message quality of service
  public static final String value = "MaxQueueLength";
}
