package CosNotification;


/**
* CosNotification/NamedPropertyRange.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotification.idl
* Thursday, February 1, 2018 2:55:08 PM BDT
*/

public final class NamedPropertyRange implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public CosNotification.PropertyRange range = null;

  public NamedPropertyRange ()
  {
  } // ctor

  public NamedPropertyRange (String _name, CosNotification.PropertyRange _range)
  {
    name = _name;
    range = _range;
  } // ctor

} // class NamedPropertyRange
