package CosNotification;


/**
* CosNotification/Priority.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotification.idl
* Thursday, February 1, 2018 2:55:08 PM BDT
*/

public interface Priority
{

  // Can take on the same values as EventReliability
  public static final String value = "Priority";
}
