package CosNotification;


/**
* CosNotification/PropertyError.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotification.idl
* Thursday, February 1, 2018 2:55:08 PM BDT
*/

public final class PropertyError implements org.omg.CORBA.portable.IDLEntity
{
  public CosNotification.QoSError_code code = null;
  public String name = null;
  public CosNotification.PropertyRange available_range = null;

  public PropertyError ()
  {
  } // ctor

  public PropertyError (CosNotification.QoSError_code _code, String _name, CosNotification.PropertyRange _available_range)
  {
    code = _code;
    name = _name;
    available_range = _available_range;
  } // ctor

} // class PropertyError
