package CosNotification;

/**
* CosNotification/PropertyHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotification.idl
* Thursday, February 1, 2018 2:55:07 PM BDT
*/

public final class PropertyHolder implements org.omg.CORBA.portable.Streamable
{
  public CosNotification.Property value = null;

  public PropertyHolder ()
  {
  }

  public PropertyHolder (CosNotification.Property initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosNotification.PropertyHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosNotification.PropertyHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosNotification.PropertyHelper.type ();
  }

}
