package CosNotification;


/**
* CosNotification/StartTime.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotification.idl
* Thursday, February 1, 2018 2:55:08 PM BDT
*/

public interface StartTime
{
  public static final String value = "StartTime";
}
