package CosNotification;

/**
* CosNotification/UnsupportedQoSHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotification.idl
* Thursday, February 1, 2018 2:55:08 PM BDT
*/

public final class UnsupportedQoSHolder implements org.omg.CORBA.portable.Streamable
{
  public CosNotification.UnsupportedQoS value = null;

  public UnsupportedQoSHolder ()
  {
  }

  public UnsupportedQoSHolder (CosNotification.UnsupportedQoS initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosNotification.UnsupportedQoSHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosNotification.UnsupportedQoSHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosNotification.UnsupportedQoSHelper.type ();
  }

}
