package CosTrading.ProxyPackage;

/**
* CosTrading/ProxyPackage/IllegalRecipeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:15 PM BDT
*/

public final class IllegalRecipeHolder implements org.omg.CORBA.portable.Streamable
{
  public CosTrading.ProxyPackage.IllegalRecipe value = null;

  public IllegalRecipeHolder ()
  {
  }

  public IllegalRecipeHolder (CosTrading.ProxyPackage.IllegalRecipe initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosTrading.ProxyPackage.IllegalRecipeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosTrading.ProxyPackage.IllegalRecipeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosTrading.ProxyPackage.IllegalRecipeHelper.type ();
  }

}
