package CosTrading.ProxyPackage;


/**
* CosTrading/ProxyPackage/NotProxyOfferId.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:15 PM BDT
*/

public final class NotProxyOfferId extends org.omg.CORBA.UserException
{
  public String id = null;

  public NotProxyOfferId ()
  {
    super(NotProxyOfferIdHelper.id());
  } // ctor

  public NotProxyOfferId (String _id)
  {
    super(NotProxyOfferIdHelper.id());
    id = _id;
  } // ctor


  public NotProxyOfferId (String $reason, String _id)
  {
    super(NotProxyOfferIdHelper.id() + "  " + $reason);
    id = _id;
  } // ctor

} // class NotProxyOfferId
