package CosTrading.ProxyPackage;

/**
* CosTrading/ProxyPackage/ProxyInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:15 PM BDT
*/

public final class ProxyInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public CosTrading.ProxyPackage.ProxyInfo value = null;

  public ProxyInfoHolder ()
  {
  }

  public ProxyInfoHolder (CosTrading.ProxyPackage.ProxyInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosTrading.ProxyPackage.ProxyInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosTrading.ProxyPackage.ProxyInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosTrading.ProxyPackage.ProxyInfoHelper.type ();
  }

}
