package CosTrading.ProxyPackage;


/**
* CosTrading/ProxyPackage/ProxyInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:15 PM BDT
*/

public final class ProxyInfo implements org.omg.CORBA.portable.IDLEntity
{
  public String type = null;
  public CosTrading.Lookup target = null;
  public CosTrading.Property properties[] = null;
  public boolean if_match_all = false;
  public String recipe = null;
  public CosTrading.Policy policies_to_pass_on[] = null;

  public ProxyInfo ()
  {
  } // ctor

  public ProxyInfo (String _type, CosTrading.Lookup _target, CosTrading.Property[] _properties, boolean _if_match_all, String _recipe, CosTrading.Policy[] _policies_to_pass_on)
  {
    type = _type;
    target = _target;
    properties = _properties;
    if_match_all = _if_match_all;
    recipe = _recipe;
    policies_to_pass_on = _policies_to_pass_on;
  } // ctor

} // class ProxyInfo
