package CosTrading;


/**
* CosTrading/Admin.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:15 PM BDT
*/


/** This interface is used to manage the various policies
 * and constraints applied by the trader.
 */
public interface Admin extends AdminOperations, CosTrading.TraderComponents, CosTrading.SupportAttributes, CosTrading.ImportAttributes, CosTrading.LinkAttributes
{
} // interface Admin
