package CosTrading;

/**
* CosTrading/AdminHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:15 PM BDT
*/


/** This interface is used to manage the various policies
 * and constraints applied by the trader.
 */
public final class AdminHolder implements org.omg.CORBA.portable.Streamable
{
  public CosTrading.Admin value = null;

  public AdminHolder ()
  {
  }

  public AdminHolder (CosTrading.Admin initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosTrading.AdminHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosTrading.AdminHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosTrading.AdminHelper.type ();
  }

}
