package CosTrading;

/**
* CosTrading/DuplicatePolicyNameHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:13 PM BDT
*/

public final class DuplicatePolicyNameHolder implements org.omg.CORBA.portable.Streamable
{
  public CosTrading.DuplicatePolicyName value = null;

  public DuplicatePolicyNameHolder ()
  {
  }

  public DuplicatePolicyNameHolder (CosTrading.DuplicatePolicyName initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosTrading.DuplicatePolicyNameHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosTrading.DuplicatePolicyNameHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosTrading.DuplicatePolicyNameHelper.type ();
  }

}
