package CosTrading;


/**
* CosTrading/DuplicatePropertyName.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:13 PM BDT
*/

public final class DuplicatePropertyName extends org.omg.CORBA.UserException
{
  public String name = null;

  public DuplicatePropertyName ()
  {
    super(DuplicatePropertyNameHelper.id());
  } // ctor

  public DuplicatePropertyName (String _name)
  {
    super(DuplicatePropertyNameHelper.id());
    name = _name;
  } // ctor


  public DuplicatePropertyName (String $reason, String _name)
  {
    super(DuplicatePropertyNameHelper.id() + "  " + $reason);
    name = _name;
  } // ctor

} // class DuplicatePropertyName
