package CosTrading;


/**
* CosTrading/DuplicatePolicyName.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:13 PM BDT
*/

public final class DuplicatePolicyName extends org.omg.CORBA.UserException
{
  public String name = null;

  public DuplicatePolicyName ()
  {
    super(DuplicatePolicyNameHelper.id());
  } // ctor

  public DuplicatePolicyName (String _name)
  {
    super(DuplicatePolicyNameHelper.id());
    name = _name;
  } // ctor


  public DuplicatePolicyName (String $reason, String _name)
  {
    super(DuplicatePolicyNameHelper.id() + "  " + $reason);
    name = _name;
  } // ctor

} // class DuplicatePolicyName
