package CosTrading;


/**
* CosTrading/IllegalPropertyName.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:13 PM BDT
*/

public final class IllegalPropertyName extends org.omg.CORBA.UserException
{
  public String name = null;

  public IllegalPropertyName ()
  {
    super(IllegalPropertyNameHelper.id());
  } // ctor

  public IllegalPropertyName (String _name)
  {
    super(IllegalPropertyNameHelper.id());
    name = _name;
  } // ctor


  public IllegalPropertyName (String $reason, String _name)
  {
    super(IllegalPropertyNameHelper.id() + "  " + $reason);
    name = _name;
  } // ctor

} // class IllegalPropertyName
