package CosTrading;


/**
* CosTrading/IllegalConstraint.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:13 PM BDT
*/

public final class IllegalConstraint extends org.omg.CORBA.UserException
{
  public String constr = null;

  public IllegalConstraint ()
  {
    super(IllegalConstraintHelper.id());
  } // ctor

  public IllegalConstraint (String _constr)
  {
    super(IllegalConstraintHelper.id());
    constr = _constr;
  } // ctor


  public IllegalConstraint (String $reason, String _constr)
  {
    super(IllegalConstraintHelper.id() + "  " + $reason);
    constr = _constr;
  } // ctor

} // class IllegalConstraint
