package CosTrading;


/**
* CosTrading/ImportAttributes.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:14 PM BDT
*/


/** This interface contains attributes that describe
 * policies used witin the trader when resolving queries.
 */
public interface ImportAttributes extends ImportAttributesOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ImportAttributes
