package CosTrading;

/**
* CosTrading/LinkHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:15 PM BDT
*/


/** This interface is used to federate traders
 * together and manage the links between them.
 */
public final class LinkHolder implements org.omg.CORBA.portable.Streamable
{
  public CosTrading.Link value = null;

  public LinkHolder ()
  {
  }

  public LinkHolder (CosTrading.Link initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosTrading.LinkHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosTrading.LinkHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosTrading.LinkHelper.type ();
  }

}
