package CosTrading;

/**
* CosTrading/LinkAttributesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:14 PM BDT
*/


/** This interface contains attributes that describe
 * policies used witin the trader when following links
 * to other linked traders.
 */
public final class LinkAttributesHolder implements org.omg.CORBA.portable.Streamable
{
  public CosTrading.LinkAttributes value = null;

  public LinkAttributesHolder ()
  {
  }

  public LinkAttributesHolder (CosTrading.LinkAttributes initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosTrading.LinkAttributesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosTrading.LinkAttributesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosTrading.LinkAttributesHelper.type ();
  }

}
