package CosTrading;


/**
* CosTrading/Link.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:15 PM BDT
*/


/** This interface is used to federate traders
 * together and manage the links between them.
 */
public interface Link extends LinkOperations, CosTrading.TraderComponents, CosTrading.SupportAttributes, CosTrading.LinkAttributes
{
} // interface Link
