package CosTrading;

/**
* CosTrading/LookupHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:14 PM BDT
*/


/** This interface is used to query the trader and retrieve
 * offers which match specified conditions and constraints.
 */
public final class LookupHolder implements org.omg.CORBA.portable.Streamable
{
  public CosTrading.Lookup value = null;

  public LookupHolder ()
  {
  }

  public LookupHolder (CosTrading.Lookup initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosTrading.LookupHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosTrading.LookupHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosTrading.LookupHelper.type ();
  }

}
