package CosTrading;


/**
* CosTrading/Lookup.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:14 PM BDT
*/


/** This interface is used to query the trader and retrieve
 * offers which match specified conditions and constraints.
 */
public interface Lookup extends LookupOperations, CosTrading.TraderComponents, CosTrading.SupportAttributes, CosTrading.ImportAttributes
{
} // interface Lookup
