package CosTrading;

/**
* CosTrading/NotImplementedHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:14 PM BDT
*/

public final class NotImplementedHolder implements org.omg.CORBA.portable.Streamable
{
  public CosTrading.NotImplemented value = null;

  public NotImplementedHolder ()
  {
  }

  public NotImplementedHolder (CosTrading.NotImplemented initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosTrading.NotImplementedHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosTrading.NotImplementedHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosTrading.NotImplementedHelper.type ();
  }

}
