package CosTrading;

/**
* CosTrading/OfferIdIteratorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:14 PM BDT
*/


/** This interface supports operations to iterate through
 * lists of OfferIds returned by the CosTrading::Admin
 * interface.
 */
public final class OfferIdIteratorHolder implements org.omg.CORBA.portable.Streamable
{
  public CosTrading.OfferIdIterator value = null;

  public OfferIdIteratorHolder ()
  {
  }

  public OfferIdIteratorHolder (CosTrading.OfferIdIterator initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosTrading.OfferIdIteratorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosTrading.OfferIdIteratorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosTrading.OfferIdIteratorHelper.type ();
  }

}
