package CosTrading;


/**
* CosTrading/PolicyNameSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:13 PM BDT
*/

public final class PolicyNameSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public PolicyNameSeqHolder ()
  {
  }

  public PolicyNameSeqHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosTrading.PolicyNameSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosTrading.PolicyNameSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosTrading.PolicyNameSeqHelper.type ();
  }

}
