package CosTrading;

/**
* CosTrading/PropertyTypeMismatchHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:13 PM BDT
*/

public final class PropertyTypeMismatchHolder implements org.omg.CORBA.portable.Streamable
{
  public CosTrading.PropertyTypeMismatch value = null;

  public PropertyTypeMismatchHolder ()
  {
  }

  public PropertyTypeMismatchHolder (CosTrading.PropertyTypeMismatch initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosTrading.PropertyTypeMismatchHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosTrading.PropertyTypeMismatchHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosTrading.PropertyTypeMismatchHelper.type ();
  }

}
