package CosTrading;


/**
* CosTrading/PropertyNameSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:13 PM BDT
*/

public final class PropertyNameSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public PropertyNameSeqHolder ()
  {
  }

  public PropertyNameSeqHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosTrading.PropertyNameSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosTrading.PropertyNameSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosTrading.PropertyNameSeqHelper.type ();
  }

}
