package CosTrading;


/**
* CosTrading/PropertyTypeMismatch.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:13 PM BDT
*/

public final class PropertyTypeMismatch extends org.omg.CORBA.UserException
{
  public String type = null;
  public CosTrading.Property prop = null;

  public PropertyTypeMismatch ()
  {
    super(PropertyTypeMismatchHelper.id());
  } // ctor

  public PropertyTypeMismatch (String _type, CosTrading.Property _prop)
  {
    super(PropertyTypeMismatchHelper.id());
    type = _type;
    prop = _prop;
  } // ctor


  public PropertyTypeMismatch (String $reason, String _type, CosTrading.Property _prop)
  {
    super(PropertyTypeMismatchHelper.id() + "  " + $reason);
    type = _type;
    prop = _prop;
  } // ctor

} // class PropertyTypeMismatch
