package CosTrading;


/**
* CosTrading/Proxy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:15 PM BDT
*/


/** This interface supports proxy offers.
 * It is not yet supported.
 */
public interface Proxy extends ProxyOperations, CosTrading.TraderComponents, CosTrading.SupportAttributes
{
} // interface Proxy
