package CosTrading;


/**
* CosTrading/ReadonlyDynamicProperty.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:13 PM BDT
*/

public final class ReadonlyDynamicProperty extends org.omg.CORBA.UserException
{
  public String type = null;
  public String name = null;

  public ReadonlyDynamicProperty ()
  {
    super(ReadonlyDynamicPropertyHelper.id());
  } // ctor

  public ReadonlyDynamicProperty (String _type, String _name)
  {
    super(ReadonlyDynamicPropertyHelper.id());
    type = _type;
    name = _name;
  } // ctor


  public ReadonlyDynamicProperty (String $reason, String _type, String _name)
  {
    super(ReadonlyDynamicPropertyHelper.id() + "  " + $reason);
    type = _type;
    name = _name;
  } // ctor

} // class ReadonlyDynamicProperty
