package CosTrading;

/**
* CosTrading/RegisterHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:14 PM BDT
*/


/** This interface is used export offers of service to
 * the trader and manage these offers.
 */
public final class RegisterHolder implements org.omg.CORBA.portable.Streamable
{
  public CosTrading.Register value = null;

  public RegisterHolder ()
  {
  }

  public RegisterHolder (CosTrading.Register initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosTrading.RegisterHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosTrading.RegisterHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosTrading.RegisterHelper.type ();
  }

}
