package CosTrading;


/**
* CosTrading/Register.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:14 PM BDT
*/


/** This interface is used export offers of service to
 * the trader and manage these offers.
 */
public interface Register extends RegisterOperations, CosTrading.TraderComponents, CosTrading.SupportAttributes
{
} // interface Register
