package CosTrading;


/**
* CosTrading/SupportAttributesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:14 PM BDT
*/


/** This interface contains attributes that describe
 * type of functionality supported by a trader service.
 */
public interface SupportAttributesOperations 
{
  boolean supports_modifiable_properties ();
  boolean supports_dynamic_properties ();
  boolean supports_proxy_offers ();
  org.omg.CORBA.Object type_repos ();
} // interface SupportAttributesOperations
