package CosTrading;


/**
* CosTrading/TraderComponentsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:14 PM BDT
*/


/** This interface has references to the componet services
 * that make up a trader. Not all services may be present,
 * depending on the type of trader.
 */
public interface TraderComponentsOperations 
{
  CosTrading.Lookup lookup_if ();
  CosTrading.Register register_if ();
  CosTrading.Link link_if ();
  CosTrading.Proxy proxy_if ();
  CosTrading.Admin admin_if ();
} // interface TraderComponentsOperations
