package CosTrading;


/**
* CosTrading/UnknownMaxLeft.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:14 PM BDT
*/

public final class UnknownMaxLeft extends org.omg.CORBA.UserException
{

  public UnknownMaxLeft ()
  {
    super(UnknownMaxLeftHelper.id());
  } // ctor


  public UnknownMaxLeft (String $reason)
  {
    super(UnknownMaxLeftHelper.id() + "  " + $reason);
  } // ctor

} // class UnknownMaxLeft
