package CosTrading;

/**
* CosTrading/UnknownMaxLeftHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosTrading.idl
* Thursday, February 1, 2018 2:55:14 PM BDT
*/

public final class UnknownMaxLeftHolder implements org.omg.CORBA.portable.Streamable
{
  public CosTrading.UnknownMaxLeft value = null;

  public UnknownMaxLeftHolder ()
  {
  }

  public UnknownMaxLeftHolder (CosTrading.UnknownMaxLeft initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosTrading.UnknownMaxLeftHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosTrading.UnknownMaxLeftHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosTrading.UnknownMaxLeftHelper.type ();
  }

}
