package org.omg.CORBA;


/**
* org/omg/CORBA/NamedValueOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/orb.idl
* Thursday, February 1, 2018 2:55:18 PM BDT
*/

public interface NamedValueOperations 
{
} // interface NamedValueOperations
