package org.omg.CORBA;

/**
* org/omg/CORBA/NamedValueHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/orb.idl
* Thursday, February 1, 2018 2:55:18 PM BDT
*/

public final class NamedValueHolder implements org.omg.CORBA.portable.Streamable
{
  public org.omg.CORBA.NamedValue value = null;

  public NamedValueHolder ()
  {
  }

  public NamedValueHolder (org.omg.CORBA.NamedValue initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.omg.CORBA.NamedValueHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.omg.CORBA.NamedValueHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.omg.CORBA.NamedValueHelper.type ();
  }

}
