package CosNotifyChannelAdmin;

/**
* CosNotifyChannelAdmin/AdminLimitHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyChannelAdmin.idl
* Thursday, February 1, 2018 2:55:10 PM BDT
*/

public final class AdminLimitHolder implements org.omg.CORBA.portable.Streamable
{
  public CosNotifyChannelAdmin.AdminLimit value = null;

  public AdminLimitHolder ()
  {
  }

  public AdminLimitHolder (CosNotifyChannelAdmin.AdminLimit initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosNotifyChannelAdmin.AdminLimitHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosNotifyChannelAdmin.AdminLimitHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosNotifyChannelAdmin.AdminLimitHelper.type ();
  }

}
