package CosNotifyChannelAdmin;


/**
* CosNotifyChannelAdmin/AdminNotFound.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyChannelAdmin.idl
* Thursday, February 1, 2018 2:55:10 PM BDT
*/

public final class AdminNotFound extends org.omg.CORBA.UserException
{

  public AdminNotFound ()
  {
    super(AdminNotFoundHelper.id());
  } // ctor


  public AdminNotFound (String $reason)
  {
    super(AdminNotFoundHelper.id() + "  " + $reason);
  } // ctor

} // class AdminNotFound
