package CosNotifyChannelAdmin;

/**
* CosNotifyChannelAdmin/AdminNotFoundHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyChannelAdmin.idl
* Thursday, February 1, 2018 2:55:10 PM BDT
*/

public final class AdminNotFoundHolder implements org.omg.CORBA.portable.Streamable
{
  public CosNotifyChannelAdmin.AdminNotFound value = null;

  public AdminNotFoundHolder ()
  {
  }

  public AdminNotFoundHolder (CosNotifyChannelAdmin.AdminNotFound initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosNotifyChannelAdmin.AdminNotFoundHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosNotifyChannelAdmin.AdminNotFoundHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosNotifyChannelAdmin.AdminNotFoundHelper.type ();
  }

}
