package CosNotifyChannelAdmin;


/**
* CosNotifyChannelAdmin/AdminIDSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyChannelAdmin.idl
* Thursday, February 1, 2018 2:55:10 PM BDT
*/


/**
    * A sequence of administration identifiers.
    */
public final class AdminIDSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public AdminIDSeqHolder ()
  {
  }

  public AdminIDSeqHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosNotifyChannelAdmin.AdminIDSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosNotifyChannelAdmin.AdminIDSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosNotifyChannelAdmin.AdminIDSeqHelper.type ();
  }

}
