package CosNotifyChannelAdmin;


/**
* CosNotifyChannelAdmin/ChannelNotFound.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyChannelAdmin.idl
* Thursday, February 1, 2018 2:55:10 PM BDT
*/

public final class ChannelNotFound extends org.omg.CORBA.UserException
{

  public ChannelNotFound ()
  {
    super(ChannelNotFoundHelper.id());
  } // ctor


  public ChannelNotFound (String $reason)
  {
    super(ChannelNotFoundHelper.id() + "  " + $reason);
  } // ctor

} // class ChannelNotFound
