package CosNotifyChannelAdmin;

/**
* CosNotifyChannelAdmin/ClientTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyChannelAdmin.idl
* Thursday, February 1, 2018 2:55:09 PM BDT
*/


/**
    * Enumeration of client types.
    */
public final class ClientTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public CosNotifyChannelAdmin.ClientType value = null;

  public ClientTypeHolder ()
  {
  }

  public ClientTypeHolder (CosNotifyChannelAdmin.ClientType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosNotifyChannelAdmin.ClientTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosNotifyChannelAdmin.ClientTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosNotifyChannelAdmin.ClientTypeHelper.type ();
  }

}
