package CosNotifyChannelAdmin;


/**
* CosNotifyChannelAdmin/ConnectionAlreadyActive.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyChannelAdmin.idl
* Thursday, February 1, 2018 2:55:09 PM BDT
*/

public final class ConnectionAlreadyActive extends org.omg.CORBA.UserException
{

  public ConnectionAlreadyActive ()
  {
    super(ConnectionAlreadyActiveHelper.id());
  } // ctor


  public ConnectionAlreadyActive (String $reason)
  {
    super(ConnectionAlreadyActiveHelper.id() + "  " + $reason);
  } // ctor

} // class ConnectionAlreadyActive
