package CosNotifyChannelAdmin;

/**
* CosNotifyChannelAdmin/ConnectionAlreadyInactiveHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyChannelAdmin.idl
* Thursday, February 1, 2018 2:55:09 PM BDT
*/

public final class ConnectionAlreadyInactiveHolder implements org.omg.CORBA.portable.Streamable
{
  public CosNotifyChannelAdmin.ConnectionAlreadyInactive value = null;

  public ConnectionAlreadyInactiveHolder ()
  {
  }

  public ConnectionAlreadyInactiveHolder (CosNotifyChannelAdmin.ConnectionAlreadyInactive initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosNotifyChannelAdmin.ConnectionAlreadyInactiveHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosNotifyChannelAdmin.ConnectionAlreadyInactiveHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosNotifyChannelAdmin.ConnectionAlreadyInactiveHelper.type ();
  }

}
