package CosNotifyChannelAdmin;

/**
* CosNotifyChannelAdmin/ConnectionAlreadyActiveHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyChannelAdmin.idl
* Thursday, February 1, 2018 2:55:09 PM BDT
*/

public final class ConnectionAlreadyActiveHolder implements org.omg.CORBA.portable.Streamable
{
  public CosNotifyChannelAdmin.ConnectionAlreadyActive value = null;

  public ConnectionAlreadyActiveHolder ()
  {
  }

  public ConnectionAlreadyActiveHolder (CosNotifyChannelAdmin.ConnectionAlreadyActive initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosNotifyChannelAdmin.ConnectionAlreadyActiveHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosNotifyChannelAdmin.ConnectionAlreadyActiveHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosNotifyChannelAdmin.ConnectionAlreadyActiveHelper.type ();
  }

}
