package CosNotifyChannelAdmin;


/**
* CosNotifyChannelAdmin/ConsumerAdmin.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyChannelAdmin.idl
* Thursday, February 1, 2018 2:55:10 PM BDT
*/


/**
    * An interface for consumer administration objects.
    */
public interface ConsumerAdmin extends ConsumerAdminOperations, CosNotification.QoSAdmin, CosNotifyComm.NotifySubscribe, CosNotifyFilter.FilterAdmin, CosEventChannelAdmin.ConsumerAdmin
{
} // interface ConsumerAdmin
