package CosNotifyChannelAdmin;


/**
* CosNotifyChannelAdmin/EventChannelFactory.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyChannelAdmin.idl
* Thursday, February 1, 2018 2:55:10 PM BDT
*/


/**
    * An interface for the event channel factory.
    */
public interface EventChannelFactory extends EventChannelFactoryOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface EventChannelFactory
