package CosNotifyChannelAdmin;

/**
* CosNotifyChannelAdmin/ObtainInfoModeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyChannelAdmin.idl
* Thursday, February 1, 2018 2:55:09 PM BDT
*/


/**
    * Enumeration of modes for obtaining subscription or offered types.
    */
public final class ObtainInfoModeHolder implements org.omg.CORBA.portable.Streamable
{
  public CosNotifyChannelAdmin.ObtainInfoMode value = null;

  public ObtainInfoModeHolder ()
  {
  }

  public ObtainInfoModeHolder (CosNotifyChannelAdmin.ObtainInfoMode initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosNotifyChannelAdmin.ObtainInfoModeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosNotifyChannelAdmin.ObtainInfoModeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosNotifyChannelAdmin.ObtainInfoModeHelper.type ();
  }

}
