package CosNotifyChannelAdmin;


/**
* CosNotifyChannelAdmin/ProxyNotFound.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyChannelAdmin.idl
* Thursday, February 1, 2018 2:55:10 PM BDT
*/

public final class ProxyNotFound extends org.omg.CORBA.UserException
{

  public ProxyNotFound ()
  {
    super(ProxyNotFoundHelper.id());
  } // ctor


  public ProxyNotFound (String $reason)
  {
    super(ProxyNotFoundHelper.id() + "  " + $reason);
  } // ctor

} // class ProxyNotFound
