package CosNotifyChannelAdmin;


/**
* CosNotifyChannelAdmin/ProxyPullSupplierOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyChannelAdmin.idl
* Thursday, February 1, 2018 2:55:09 PM BDT
*/


/**
    * An interface for proxy pull suppliers.
    */
public interface ProxyPullSupplierOperations  extends CosNotifyChannelAdmin.ProxySupplierOperations, CosNotifyComm.PullSupplierOperations
{

  /**
         * Connect an any type pull consumer to this proxy.
         * @parm <code>pull_consumer</code> - The <code>PullConsumer</code>
         * object reference.
         * @raises AlreadyConnected If this consumer is already connected.
         */
  void connect_any_pull_consumer (CosEventComm.PullConsumer pull_consumer) throws CosEventChannelAdmin.AlreadyConnected;
} // interface ProxyPullSupplierOperations
