package CosNotifyChannelAdmin;


/**
* CosNotifyChannelAdmin/ProxyConsumerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyChannelAdmin.idl
* Thursday, February 1, 2018 2:55:09 PM BDT
*/


/**
    * An interface for proxy consumers.
    */
public interface ProxyConsumerOperations  extends CosNotification.QoSAdminOperations, CosNotifyFilter.FilterAdminOperations
{

  /**
         * The type of this proxy.
         */
  CosNotifyChannelAdmin.ProxyType MyType ();

  /**
         * The administration object that created this proxy.
         */
  CosNotifyChannelAdmin.SupplierAdmin MyAdmin ();

  /**
         * Get a list of event type names which represent the event types that
         * consumers connected to this channel are interested in receiving.
         * @parm <code>mode</code> - The mode of type retrieval.
         * @returns A sequence of event type names.
         */
  CosNotification.EventType[] obtain_subscription_types (CosNotifyChannelAdmin.ObtainInfoMode mode);

  /**
         * Validate whether or not this proxy can honour the specified 
         * quality of service requirements.
         * @parm <code>required_qos</code> - Quality of service name-value
         * pairs which a client is interested in validating.
         * @parm <code>available_qos</code> - Quality of service settings that
         * this proxy can support in addition to the ones in the input sequence.
         * @raises UnsupportedQoS If any of the quality of service settings
         * in the input sequence could not be honoured.
         */
  void validate_event_qos (CosNotification.Property[] required_qos, CosNotification.NamedPropertyRangeSeqHolder available_qos) throws CosNotification.UnsupportedQoS;
} // interface ProxyConsumerOperations
