package CosNotifyChannelAdmin;


/**
* CosNotifyChannelAdmin/ProxyPushSupplier.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyChannelAdmin.idl
* Thursday, February 1, 2018 2:55:09 PM BDT
*/


/**
    * An interface for proxy push suppliers.
    */
public interface ProxyPushSupplier extends ProxyPushSupplierOperations, CosNotifyChannelAdmin.ProxySupplier, CosNotifyComm.PushSupplier
{
} // interface ProxyPushSupplier
