package CosNotifyChannelAdmin;


/**
* CosNotifyChannelAdmin/ProxyPullConsumer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyChannelAdmin.idl
* Thursday, February 1, 2018 2:55:09 PM BDT
*/


/**
    * An interface for proxy pull consumers.
    */
public interface ProxyPullConsumer extends ProxyPullConsumerOperations, CosNotifyChannelAdmin.ProxyConsumer, CosNotifyComm.PullConsumer
{
} // interface ProxyPullConsumer
