package CosNotifyChannelAdmin;


/**
* CosNotifyChannelAdmin/ProxyPushConsumerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyChannelAdmin.idl
* Thursday, February 1, 2018 2:55:09 PM BDT
*/


/**
    * An interface for proxy push consumers.
    */
public interface ProxyPushConsumerOperations  extends CosNotifyChannelAdmin.ProxyConsumerOperations, CosNotifyComm.PushConsumerOperations
{

  /**
         * Connect an any type push supplier to this proxy.
         * @parm <code>push_supplier</code> - The <code>PushSupplier</code>
         * object reference.
         * @raises AlreadyConnected If this supplier is already connected.
         */
  void connect_any_push_supplier (CosEventComm.PushSupplier push_supplier) throws CosEventChannelAdmin.AlreadyConnected;
} // interface ProxyPushConsumerOperations
