package CosNotifyChannelAdmin;


/**
* CosNotifyChannelAdmin/ProxySupplierOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyChannelAdmin.idl
* Thursday, February 1, 2018 2:55:09 PM BDT
*/


/**
    * An interface for proxy suppliers.
    */
public interface ProxySupplierOperations  extends CosNotification.QoSAdminOperations, CosNotifyFilter.FilterAdminOperations
{

  /**
         * The type of this proxy.
         */
  CosNotifyChannelAdmin.ProxyType MyType ();

  /**
         * The administration object that created this proxy.
         */
  CosNotifyChannelAdmin.ConsumerAdmin MyAdmin ();

  /**
         * A mapping filter which if a non-nil reference will be consulted 
         * for resolving the priority of the event.
         */
  CosNotifyFilter.MappingFilter priority_filter ();

  /**
         * A mapping filter which if a non-nil reference will be consulted 
         * for resolving the priority of the event.
         */
  void priority_filter (CosNotifyFilter.MappingFilter newPriority_filter);

  /**
         * A filter which if a non-nil reference will be consulted 
         * for resolving the priority of the event.
         */
  CosNotifyFilter.MappingFilter lifetime_filter ();

  /**
         * A filter which if a non-nil reference will be consulted 
         * for resolving the priority of the event.
         */
  void lifetime_filter (CosNotifyFilter.MappingFilter newLifetime_filter);

  /**
         * Get a list of event type names that this proxy can potentially
         * forward to its associated consumers.
         * @parm <code>mode</code> - The mode of type retrieval.
         * @returns A sequence of event type names.
         */
  CosNotification.EventType[] obtain_offered_types (CosNotifyChannelAdmin.ObtainInfoMode mode);

  /**
         * Validate whether or not this proxy can honour the specified 
         * quality of service requirements.
         * @parm <code>required_qos</code> - Quality of service name-value
         * pairs which a client is interested in validating.
         * @parm <code>available_qos</code> - Quality of service settings that
         * this proxy can support in addition to the ones in the input sequence.
         * @raises UnsupportedQoS If any of the quality of service settings
         * in the input sequence could not be honoured.
         */
  void validate_event_qos (CosNotification.Property[] required_qos, CosNotification.NamedPropertyRangeSeqHolder available_qos) throws CosNotification.UnsupportedQoS;
} // interface ProxySupplierOperations
