package CosNotifyChannelAdmin;


/**
* CosNotifyChannelAdmin/SequenceProxyPushSupplier.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyChannelAdmin.idl
* Thursday, February 1, 2018 2:55:09 PM BDT
*/


/**
    * An interface for sequence proxy push suppliers.
    */
public interface SequenceProxyPushSupplier extends SequenceProxyPushSupplierOperations, CosNotifyChannelAdmin.ProxySupplier, CosNotifyComm.SequencePushSupplier
{
} // interface SequenceProxyPushSupplier
