package CosNotifyChannelAdmin;


/**
* CosNotifyChannelAdmin/SequenceProxyPushConsumerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyChannelAdmin.idl
* Thursday, February 1, 2018 2:55:09 PM BDT
*/


/**
    * An interface for sequence proxy push consumers.
    */
public interface SequenceProxyPushConsumerOperations  extends CosNotifyChannelAdmin.ProxyConsumerOperations, CosNotifyComm.SequencePushConsumerOperations
{

  /**
         * Connect a sequence type push supplier to this proxy.
         * @parm <code>push_supplier</code> - The <code>PushSupplier</code>
         * object reference.
         * @raises AlreadyConnected If this supplier is already connected.
         */
  void connect_sequence_push_supplier (CosNotifyComm.SequencePushSupplier push_supplier) throws CosEventChannelAdmin.AlreadyConnected;
} // interface SequenceProxyPushConsumerOperations
