package CosNotifyChannelAdmin;


/**
* CosNotifyChannelAdmin/SequenceProxyPullSupplierOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyChannelAdmin.idl
* Thursday, February 1, 2018 2:55:09 PM BDT
*/


/**
    * An interface for sequence proxy pull suppliers.
    */
public interface SequenceProxyPullSupplierOperations  extends CosNotifyChannelAdmin.ProxySupplierOperations, CosNotifyComm.SequencePullSupplierOperations
{

  /**
         * Connect a sequence type pull consumer to this proxy.
         * @parm <code>pull_consumer</code> - The <code>PullConsumer</code>
         * object reference.
         * @raises AlreadyConnected If this consumer is already connected.
         */
  void connect_sequence_pull_consumer (CosNotifyComm.SequencePullConsumer pull_consumer) throws CosEventChannelAdmin.AlreadyConnected;
} // interface SequenceProxyPullSupplierOperations
