package CosNotifyChannelAdmin;


/**
* CosNotifyChannelAdmin/SequenceProxyPushConsumer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyChannelAdmin.idl
* Thursday, February 1, 2018 2:55:09 PM BDT
*/


/**
    * An interface for sequence proxy push consumers.
    */
public interface SequenceProxyPushConsumer extends SequenceProxyPushConsumerOperations, CosNotifyChannelAdmin.ProxyConsumer, CosNotifyComm.SequencePushConsumer
{
} // interface SequenceProxyPushConsumer
