package CosNotifyChannelAdmin;


/**
* CosNotifyChannelAdmin/StructuredProxyPullSupplier.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyChannelAdmin.idl
* Thursday, February 1, 2018 2:55:09 PM BDT
*/


/**
    * An interface for structured proxy pull suppliers.
    */
public interface StructuredProxyPullSupplier extends StructuredProxyPullSupplierOperations, CosNotifyChannelAdmin.ProxySupplier, CosNotifyComm.StructuredPullSupplier
{
} // interface StructuredProxyPullSupplier
