package CosNotifyChannelAdmin;


/**
* CosNotifyChannelAdmin/StructuredProxyPushSupplier.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyChannelAdmin.idl
* Thursday, February 1, 2018 2:55:09 PM BDT
*/


/**
    * An interface for structured proxy push suppliers.
    */
public interface StructuredProxyPushSupplier extends StructuredProxyPushSupplierOperations, CosNotifyChannelAdmin.ProxySupplier, CosNotifyComm.StructuredPushSupplier
{
} // interface StructuredProxyPushSupplier
