package CosNotifyChannelAdmin;

/**
* CosNotifyChannelAdmin/StructuredProxyPullSupplierHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyChannelAdmin.idl
* Thursday, February 1, 2018 2:55:09 PM BDT
*/


/**
    * An interface for structured proxy pull suppliers.
    */
public final class StructuredProxyPullSupplierHolder implements org.omg.CORBA.portable.Streamable
{
  public CosNotifyChannelAdmin.StructuredProxyPullSupplier value = null;

  public StructuredProxyPullSupplierHolder ()
  {
  }

  public StructuredProxyPullSupplierHolder (CosNotifyChannelAdmin.StructuredProxyPullSupplier initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosNotifyChannelAdmin.StructuredProxyPullSupplierHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosNotifyChannelAdmin.StructuredProxyPullSupplierHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosNotifyChannelAdmin.StructuredProxyPullSupplierHelper.type ();
  }

}
