package CosNotifyChannelAdmin;


/**
* CosNotifyChannelAdmin/StructuredProxyPullConsumerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyChannelAdmin.idl
* Thursday, February 1, 2018 2:55:09 PM BDT
*/


/**
    * An interface for structured proxy pull consumers.
    */
public interface StructuredProxyPullConsumerOperations  extends CosNotifyChannelAdmin.ProxyConsumerOperations, CosNotifyComm.StructuredPullConsumerOperations
{

  /**
         * Connect a structured type pull supplier to this proxy.
         * @parm <code>pull_supplier</code> - The <code>PullSupplier</code>
         * object reference.
         * @raises AlreadyConnected If this supplier is already connected.
         * @raises TypeError Illegal supplier type.
         */
  void connect_structured_pull_supplier (CosNotifyComm.StructuredPullSupplier pull_supplier) throws CosEventChannelAdmin.AlreadyConnected, CosEventChannelAdmin.TypeError;

  /**
         * Causes this proxy to stop pulling events from its supplier.
         * @raises ConnectionAlreadyInactive Proxy already stopped.
         * @raises NotConnected Proxy not connected.
         */
  void suspend_connection () throws CosNotifyChannelAdmin.ConnectionAlreadyInactive, CosNotifyChannelAdmin.NotConnected;

  /**
         * Causes this proxy to start pulling events from its supplier.
         * @raises ConnectionAlreadyActive Proxy already started.
         * @raises NotConnected Proxy not connected.
         */
  void resume_connection () throws CosNotifyChannelAdmin.ConnectionAlreadyActive, CosNotifyChannelAdmin.NotConnected;
} // interface StructuredProxyPullConsumerOperations
