package CosNotifyChannelAdmin;


/**
* CosNotifyChannelAdmin/SupplierAdmin.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyChannelAdmin.idl
* Thursday, February 1, 2018 2:55:10 PM BDT
*/


/**
    * An interface for supplier administration objects.
    */
public interface SupplierAdmin extends SupplierAdminOperations, CosNotification.QoSAdmin, CosNotifyComm.NotifyPublish, CosNotifyFilter.FilterAdmin, CosEventChannelAdmin.SupplierAdmin
{
} // interface SupplierAdmin
