package DsEventLogAdmin;

/**
* DsEventLogAdmin/EventLogFactoryHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsEventLogAdmin.idl
* Thursday, February 1, 2018 2:55:15 PM BDT
*/

public final class EventLogFactoryHolder implements org.omg.CORBA.portable.Streamable
{
  public DsEventLogAdmin.EventLogFactory value = null;

  public EventLogFactoryHolder ()
  {
  }

  public EventLogFactoryHolder (DsEventLogAdmin.EventLogFactory initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DsEventLogAdmin.EventLogFactoryHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DsEventLogAdmin.EventLogFactoryHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DsEventLogAdmin.EventLogFactoryHelper.type ();
  }

}
