package DsEventLogAdmin;

/**
* DsEventLogAdmin/EventLogHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsEventLogAdmin.idl
* Thursday, February 1, 2018 2:55:15 PM BDT
*/

public final class EventLogHolder implements org.omg.CORBA.portable.Streamable
{
  public DsEventLogAdmin.EventLog value = null;

  public EventLogHolder ()
  {
  }

  public EventLogHolder (DsEventLogAdmin.EventLog initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DsEventLogAdmin.EventLogHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DsEventLogAdmin.EventLogHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DsEventLogAdmin.EventLogHelper.type ();
  }

}
