package DsEventLogAdmin;


/**
* DsEventLogAdmin/EventLogOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsEventLogAdmin.idl
* Thursday, February 1, 2018 2:55:15 PM BDT
*/

public interface EventLogOperations  extends DsLogAdmin.LogOperations, CosEventChannelAdmin.EventChannelOperations
{
} // interface EventLogOperations
