package DsEventLogAdmin;


/**
* DsEventLogAdmin/EventLogFactoryOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsEventLogAdmin.idl
* Thursday, February 1, 2018 2:55:15 PM BDT
*/

public interface EventLogFactoryOperations  extends DsLogAdmin.LogMgrOperations, CosEventChannelAdmin.ConsumerAdminOperations
{
  DsEventLogAdmin.EventLog create (short full_action, long max_size, short[] thresholds, org.omg.CORBA.IntHolder id) throws DsLogAdmin.InvalidLogFullAction, DsLogAdmin.InvalidThreshold;
  DsEventLogAdmin.EventLog create_with_id (int id, short full_action, long max_size, short[] thresholds) throws DsLogAdmin.LogIdAlreadyExists, DsLogAdmin.InvalidLogFullAction, DsLogAdmin.InvalidThreshold;
} // interface EventLogFactoryOperations
