package CosNotifyComm;


/**
* CosNotifyComm/NotifySubscribe.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyComm.idl
* Thursday, February 1, 2018 2:55:10 PM BDT
*/


/**
    * An interface used by event subscribers.
    */
public interface NotifySubscribe extends NotifySubscribeOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface NotifySubscribe
