package CosNotifyComm;

/**
* CosNotifyComm/NotifyPublishHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyComm.idl
* Thursday, February 1, 2018 2:55:10 PM BDT
*/


/**
    * An interface used by event publishers.
    */
public final class NotifyPublishHolder implements org.omg.CORBA.portable.Streamable
{
  public CosNotifyComm.NotifyPublish value = null;

  public NotifyPublishHolder ()
  {
  }

  public NotifyPublishHolder (CosNotifyComm.NotifyPublish initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosNotifyComm.NotifyPublishHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosNotifyComm.NotifyPublishHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosNotifyComm.NotifyPublishHelper.type ();
  }

}
