package CosNotifyComm;


/**
* CosNotifyComm/NotifyPublish.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyComm.idl
* Thursday, February 1, 2018 2:55:10 PM BDT
*/


/**
    * An interface used by event publishers.
    */
public interface NotifyPublish extends NotifyPublishOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface NotifyPublish
