package CosNotifyComm;


/**
* CosNotifyComm/PullConsumer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyComm.idl
* Thursday, February 1, 2018 2:55:10 PM BDT
*/


/**
    * An interface for pull consumers.
    */
public interface PullConsumer extends PullConsumerOperations, CosNotifyComm.NotifyPublish, CosEventComm.PullConsumer
{
} // interface PullConsumer
