package CosNotifyComm;


/**
* CosNotifyComm/PushSupplierOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyComm.idl
* Thursday, February 1, 2018 2:55:11 PM BDT
*/


/**
    * An interface for push suppliers.
    */
public interface PushSupplierOperations  extends CosNotifyComm.NotifySubscribeOperations, CosEventComm.PushSupplierOperations
{
} // interface PushSupplierOperations
