package CosNotifyComm;


/**
* CosNotifyComm/SequencePullConsumerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyComm.idl
* Thursday, February 1, 2018 2:55:11 PM BDT
*/


/**
    * An interface for sequences pull consumers.
    */
public interface SequencePullConsumerOperations  extends CosNotifyComm.NotifyPublishOperations
{

  /**
         * Disconnect this pull consumer.
         */
  void disconnect_sequence_pull_consumer ();
} // interface SequencePullConsumerOperations
