package CosNotifyComm;


/**
* CosNotifyComm/SequencePushConsumer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyComm.idl
* Thursday, February 1, 2018 2:55:11 PM BDT
*/


/**
    * An interface for sequence push consumers.
    */
public interface SequencePushConsumer extends SequencePushConsumerOperations, CosNotifyComm.NotifyPublish, org.omg.CORBA.portable.IDLEntity 
{
} // interface SequencePushConsumer
