package CosNotifyComm;

/**
* CosNotifyComm/SequencePullSupplierHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyComm.idl
* Thursday, February 1, 2018 2:55:11 PM BDT
*/


/**
    * An interface for sequences pull suppliers.
    */
public final class SequencePullSupplierHolder implements org.omg.CORBA.portable.Streamable
{
  public CosNotifyComm.SequencePullSupplier value = null;

  public SequencePullSupplierHolder ()
  {
  }

  public SequencePullSupplierHolder (CosNotifyComm.SequencePullSupplier initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosNotifyComm.SequencePullSupplierHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosNotifyComm.SequencePullSupplierHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosNotifyComm.SequencePullSupplierHelper.type ();
  }

}
