package CosNotifyComm;


/**
* CosNotifyComm/SequencePullSupplier.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyComm.idl
* Thursday, February 1, 2018 2:55:11 PM BDT
*/


/**
    * An interface for sequences pull suppliers.
    */
public interface SequencePullSupplier extends SequencePullSupplierOperations, CosNotifyComm.NotifySubscribe, org.omg.CORBA.portable.IDLEntity 
{
} // interface SequencePullSupplier
