package CosNotifyComm;


/**
* CosNotifyComm/SequencePushConsumerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyComm.idl
* Thursday, February 1, 2018 2:55:11 PM BDT
*/


/**
    * An interface for sequence push consumers.
    */
public interface SequencePushConsumerOperations  extends CosNotifyComm.NotifyPublishOperations
{

  /**
         * Push a sequence of events onto this consumer.
         * @parm <code>notifications</code> - The event sequence.
         * @raises Disconnected If this consumer is disconnected.
         */
  void push_structured_events (CosNotification.StructuredEvent[] notifications) throws CosEventComm.Disconnected;

  /**
         * Disconnect this push consumer.
         */
  void disconnect_sequence_push_consumer ();
} // interface SequencePushConsumerOperations
