package CosNotifyComm;


/**
* CosNotifyComm/SequencePullConsumer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyComm.idl
* Thursday, February 1, 2018 2:55:11 PM BDT
*/


/**
    * An interface for sequences pull consumers.
    */
public interface SequencePullConsumer extends SequencePullConsumerOperations, CosNotifyComm.NotifyPublish, org.omg.CORBA.portable.IDLEntity 
{
} // interface SequencePullConsumer
