package CosNotifyComm;


/**
* CosNotifyComm/StructuredPushSupplierOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyComm.idl
* Thursday, February 1, 2018 2:55:11 PM BDT
*/


/**
    * An interface for structured push suppliers.
    */
public interface StructuredPushSupplierOperations  extends CosNotifyComm.NotifySubscribeOperations
{

  /**
         * Disconnect this push supplier.
         */
  void disconnect_structured_push_supplier ();
} // interface StructuredPushSupplierOperations
