package CosNotifyComm;


/**
* CosNotifyComm/StructuredPullConsumerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyComm.idl
* Thursday, February 1, 2018 2:55:11 PM BDT
*/


/**
    * An interface for structured pull consumers.
    */
public interface StructuredPullConsumerOperations  extends CosNotifyComm.NotifyPublishOperations
{

  /**
         * Disconnect this structured pull consumer.
         */
  void disconnect_structured_pull_consumer ();
} // interface StructuredPullConsumerOperations
