package CosNotifyComm;

/**
* CosNotifyComm/StructuredPullConsumerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyComm.idl
* Thursday, February 1, 2018 2:55:11 PM BDT
*/


/**
    * An interface for structured pull consumers.
    */
public final class StructuredPullConsumerHolder implements org.omg.CORBA.portable.Streamable
{
  public CosNotifyComm.StructuredPullConsumer value = null;

  public StructuredPullConsumerHolder ()
  {
  }

  public StructuredPullConsumerHolder (CosNotifyComm.StructuredPullConsumer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CosNotifyComm.StructuredPullConsumerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CosNotifyComm.StructuredPullConsumerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CosNotifyComm.StructuredPullConsumerHelper.type ();
  }

}
