package CosNotifyComm;


/**
* CosNotifyComm/StructuredPullSupplierOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyComm.idl
* Thursday, February 1, 2018 2:55:11 PM BDT
*/


/**
    * An interface for structured pull suppliers.
    */
public interface StructuredPullSupplierOperations  extends CosNotifyComm.NotifySubscribeOperations
{

  /**
         * Pull a structured event from this supplier
         * @returns The structured event.
         * @raises Disconnected If this supplier is disconnected.
         */
  CosNotification.StructuredEvent pull_structured_event () throws CosEventComm.Disconnected;

  /**
         * Try to pull a structured event from this supplier.
         * @parm <code>has_event</code> - boolean indicating if supplier has
         * an event.
         * @returns The structured event if has_event is true.
         * @raises Disconnected If this supplier is disconnected.
         */
  CosNotification.StructuredEvent try_pull_structured_event (org.omg.CORBA.BooleanHolder has_event) throws CosEventComm.Disconnected;

  /**
         * Disconnect this pull supplier.
         */
  void disconnect_structured_pull_supplier ();
} // interface StructuredPullSupplierOperations
