package CosNotifyComm;


/**
* CosNotifyComm/StructuredPullConsumer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/CosNotifyComm.idl
* Thursday, February 1, 2018 2:55:11 PM BDT
*/


/**
    * An interface for structured pull consumers.
    */
public interface StructuredPullConsumer extends StructuredPullConsumerOperations, CosNotifyComm.NotifyPublish, org.omg.CORBA.portable.IDLEntity 
{
} // interface StructuredPullConsumer
