package DsLogAdmin;


/**
* DsLogAdmin/AdministrativeState.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsLogAdmin.idl
* Thursday, February 1, 2018 2:55:17 PM BDT
*/

public class AdministrativeState implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static DsLogAdmin.AdministrativeState[] __array = new DsLogAdmin.AdministrativeState [__size];

  public static final int _locked = 0;
  public static final DsLogAdmin.AdministrativeState locked = new DsLogAdmin.AdministrativeState(_locked);
  public static final int _unlocked = 1;
  public static final DsLogAdmin.AdministrativeState unlocked = new DsLogAdmin.AdministrativeState(_unlocked);

  public int value ()
  {
    return __value;
  }

  public static DsLogAdmin.AdministrativeState from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected AdministrativeState (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class AdministrativeState
