package DsLogAdmin;


/**
* DsLogAdmin/BasicLogFactory.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsLogAdmin.idl
* Thursday, February 1, 2018 2:55:17 PM BDT
*/

public interface BasicLogFactory extends BasicLogFactoryOperations, DsLogAdmin.LogMgr, org.omg.CORBA.portable.IDLEntity 
{
} // interface BasicLogFactory
