package DsLogAdmin;


/**
* DsLogAdmin/BasicLog.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsLogAdmin.idl
* Thursday, February 1, 2018 2:55:17 PM BDT
*/

public interface BasicLog extends BasicLogOperations, DsLogAdmin.Log, org.omg.CORBA.portable.IDLEntity 
{
} // interface BasicLog
