package DsLogAdmin;


/**
* DsLogAdmin/BasicLogFactoryOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsLogAdmin.idl
* Thursday, February 1, 2018 2:55:17 PM BDT
*/

public interface BasicLogFactoryOperations  extends DsLogAdmin.LogMgrOperations
{
  DsLogAdmin.BasicLog create (short full_action, long max_size, org.omg.CORBA.IntHolder id) throws DsLogAdmin.InvalidLogFullAction;
  DsLogAdmin.BasicLog create_with_id (int id, short full_action, long max_size) throws DsLogAdmin.LogIdAlreadyExists, DsLogAdmin.InvalidLogFullAction;
} // interface BasicLogFactoryOperations
