package DsLogAdmin;

/**
* DsLogAdmin/BasicLogHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsLogAdmin.idl
* Thursday, February 1, 2018 2:55:17 PM BDT
*/

public final class BasicLogHolder implements org.omg.CORBA.portable.Streamable
{
  public DsLogAdmin.BasicLog value = null;

  public BasicLogHolder ()
  {
  }

  public BasicLogHolder (DsLogAdmin.BasicLog initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DsLogAdmin.BasicLogHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DsLogAdmin.BasicLogHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DsLogAdmin.BasicLogHelper.type ();
  }

}
