package DsLogAdmin;


/**
* DsLogAdmin/default_grammar.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsLogAdmin.idl
* Thursday, February 1, 2018 2:55:16 PM BDT
*/

public interface default_grammar
{
  public static final String value = "EXTENDED_TCL";
}
