package DsLogAdmin;

/**
* DsLogAdmin/ForwardingStateHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsLogAdmin.idl
* Thursday, February 1, 2018 2:55:17 PM BDT
*/


// logging on/off
public final class ForwardingStateHolder implements org.omg.CORBA.portable.Streamable
{
  public DsLogAdmin.ForwardingState value = null;

  public ForwardingStateHolder ()
  {
  }

  public ForwardingStateHolder (DsLogAdmin.ForwardingState initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DsLogAdmin.ForwardingStateHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DsLogAdmin.ForwardingStateHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DsLogAdmin.ForwardingStateHelper.type ();
  }

}
