package DsLogAdmin;


/**
* DsLogAdmin/halt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsLogAdmin.idl
* Thursday, February 1, 2018 2:55:16 PM BDT
*/

public interface halt
{
  public static final short value = (short)(1);
}
