package DsLogAdmin;


/**
* DsLogAdmin/InvalidRecordId.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsLogAdmin.idl
* Thursday, February 1, 2018 2:55:16 PM BDT
*/

public final class InvalidRecordId extends org.omg.CORBA.UserException
{

  public InvalidRecordId ()
  {
    super(InvalidRecordIdHelper.id());
  } // ctor


  public InvalidRecordId (String $reason)
  {
    super(InvalidRecordIdHelper.id() + "  " + $reason);
  } // ctor

} // class InvalidRecordId
