package DsLogAdmin;

/**
* DsLogAdmin/InvalidAttributeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsLogAdmin.idl
* Thursday, February 1, 2018 2:55:16 PM BDT
*/

public final class InvalidAttributeHolder implements org.omg.CORBA.portable.Streamable
{
  public DsLogAdmin.InvalidAttribute value = null;

  public InvalidAttributeHolder ()
  {
  }

  public InvalidAttributeHolder (DsLogAdmin.InvalidAttribute initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DsLogAdmin.InvalidAttributeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DsLogAdmin.InvalidAttributeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DsLogAdmin.InvalidAttributeHelper.type ();
  }

}
