package DsLogAdmin;


/**
* DsLogAdmin/InvalidThreshold.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsLogAdmin.idl
* Thursday, February 1, 2018 2:55:16 PM BDT
*/

public final class InvalidThreshold extends org.omg.CORBA.UserException
{

  public InvalidThreshold ()
  {
    super(InvalidThresholdHelper.id());
  } // ctor


  public InvalidThreshold (String $reason)
  {
    super(InvalidThresholdHelper.id() + "  " + $reason);
  } // ctor

} // class InvalidThreshold
