package DsLogAdmin;


/**
* DsLogAdmin/InvalidConstraint.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsLogAdmin.idl
* Thursday, February 1, 2018 2:55:16 PM BDT
*/

public final class InvalidConstraint extends org.omg.CORBA.UserException
{

  public InvalidConstraint ()
  {
    super(InvalidConstraintHelper.id());
  } // ctor


  public InvalidConstraint (String $reason)
  {
    super(InvalidConstraintHelper.id() + "  " + $reason);
  } // ctor

} // class InvalidConstraint
