package DsLogAdmin;


/**
* DsLogAdmin/InvalidLogFullAction.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsLogAdmin.idl
* Thursday, February 1, 2018 2:55:16 PM BDT
*/

public final class InvalidLogFullAction extends org.omg.CORBA.UserException
{

  public InvalidLogFullAction ()
  {
    super(InvalidLogFullActionHelper.id());
  } // ctor


  public InvalidLogFullAction (String $reason)
  {
    super(InvalidLogFullActionHelper.id() + "  " + $reason);
  } // ctor

} // class InvalidLogFullAction
