package DsLogAdmin;


/**
* DsLogAdmin/InvalidMask.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsLogAdmin.idl
* Thursday, February 1, 2018 2:55:16 PM BDT
*/

public final class InvalidMask extends org.omg.CORBA.UserException
{

  public InvalidMask ()
  {
    super(InvalidMaskHelper.id());
  } // ctor


  public InvalidMask (String $reason)
  {
    super(InvalidMaskHelper.id() + "  " + $reason);
  } // ctor

} // class InvalidMask
