package DsLogAdmin;


/**
* DsLogAdmin/InvalidTimeInterval.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsLogAdmin.idl
* Thursday, February 1, 2018 2:55:16 PM BDT
*/

public final class InvalidTimeInterval extends org.omg.CORBA.UserException
{

  public InvalidTimeInterval ()
  {
    super(InvalidTimeIntervalHelper.id());
  } // ctor


  public InvalidTimeInterval (String $reason)
  {
    super(InvalidTimeIntervalHelper.id() + "  " + $reason);
  } // ctor

} // class InvalidTimeInterval
