package DsLogAdmin;

/**
* DsLogAdmin/InvalidRecordIdHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsLogAdmin.idl
* Thursday, February 1, 2018 2:55:16 PM BDT
*/

public final class InvalidRecordIdHolder implements org.omg.CORBA.portable.Streamable
{
  public DsLogAdmin.InvalidRecordId value = null;

  public InvalidRecordIdHolder ()
  {
  }

  public InvalidRecordIdHolder (DsLogAdmin.InvalidRecordId initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DsLogAdmin.InvalidRecordIdHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DsLogAdmin.InvalidRecordIdHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DsLogAdmin.InvalidRecordIdHelper.type ();
  }

}
