package DsLogAdmin;

/**
* DsLogAdmin/InvalidMaskHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsLogAdmin.idl
* Thursday, February 1, 2018 2:55:16 PM BDT
*/

public final class InvalidMaskHolder implements org.omg.CORBA.portable.Streamable
{
  public DsLogAdmin.InvalidMask value = null;

  public InvalidMaskHolder ()
  {
  }

  public InvalidMaskHolder (DsLogAdmin.InvalidMask initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DsLogAdmin.InvalidMaskHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DsLogAdmin.InvalidMaskHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DsLogAdmin.InvalidMaskHelper.type ();
  }

}
