package DsLogAdmin;


/**
* DsLogAdmin/IteratorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsLogAdmin.idl
* Thursday, February 1, 2018 2:55:16 PM BDT
*/


// result of querying the Log
public interface IteratorOperations 
{
  DsLogAdmin.LogRecord[] get (int position, int how_many) throws DsLogAdmin.InvalidParam;
  void destroy ();
} // interface IteratorOperations
