package DsLogAdmin;

/**
* DsLogAdmin/LogDisabledHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsLogAdmin.idl
* Thursday, February 1, 2018 2:55:16 PM BDT
*/

public final class LogDisabledHolder implements org.omg.CORBA.portable.Streamable
{
  public DsLogAdmin.LogDisabled value = null;

  public LogDisabledHolder ()
  {
  }

  public LogDisabledHolder (DsLogAdmin.LogDisabled initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DsLogAdmin.LogDisabledHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DsLogAdmin.LogDisabledHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DsLogAdmin.LogDisabledHelper.type ();
  }

}
