package DsLogAdmin;

/**
* DsLogAdmin/LogFullHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsLogAdmin.idl
* Thursday, February 1, 2018 2:55:16 PM BDT
*/

public final class LogFullHolder implements org.omg.CORBA.portable.Streamable
{
  public DsLogAdmin.LogFull value = null;

  public LogFullHolder ()
  {
  }

  public LogFullHolder (DsLogAdmin.LogFull initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DsLogAdmin.LogFullHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DsLogAdmin.LogFullHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DsLogAdmin.LogFullHelper.type ();
  }

}
