package DsLogAdmin;

/**
* DsLogAdmin/LogLockedHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsLogAdmin.idl
* Thursday, February 1, 2018 2:55:16 PM BDT
*/

public final class LogLockedHolder implements org.omg.CORBA.portable.Streamable
{
  public DsLogAdmin.LogLocked value = null;

  public LogLockedHolder ()
  {
  }

  public LogLockedHolder (DsLogAdmin.LogLocked initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DsLogAdmin.LogLockedHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DsLogAdmin.LogLockedHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DsLogAdmin.LogLockedHelper.type ();
  }

}
