package DsLogAdmin;


/**
* DsLogAdmin/LogLocked.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsLogAdmin.idl
* Thursday, February 1, 2018 2:55:16 PM BDT
*/

public final class LogLocked extends org.omg.CORBA.UserException
{

  public LogLocked ()
  {
    super(LogLockedHelper.id());
  } // ctor


  public LogLocked (String $reason)
  {
    super(LogLockedHelper.id() + "  " + $reason);
  } // ctor

} // class LogLocked
