package DsLogAdmin;


/**
* DsLogAdmin/LogMgrOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsLogAdmin.idl
* Thursday, February 1, 2018 2:55:17 PM BDT
*/

public interface LogMgrOperations 
{
  DsLogAdmin.Log[] list_logs ();
  DsLogAdmin.Log find_log (int id);
  int[] list_logs_by_id ();
} // interface LogMgrOperations
