package DsLogAdmin;


/**
* DsLogAdmin/LogOffDuty.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsLogAdmin.idl
* Thursday, February 1, 2018 2:55:16 PM BDT
*/

public final class LogOffDuty extends org.omg.CORBA.UserException
{

  public LogOffDuty ()
  {
    super(LogOffDutyHelper.id());
  } // ctor


  public LogOffDuty (String $reason)
  {
    super(LogOffDutyHelper.id() + "  " + $reason);
  } // ctor

} // class LogOffDuty
