package DsLogAdmin;

/**
* DsLogAdmin/LogOffDutyHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsLogAdmin.idl
* Thursday, February 1, 2018 2:55:16 PM BDT
*/

public final class LogOffDutyHolder implements org.omg.CORBA.portable.Streamable
{
  public DsLogAdmin.LogOffDuty value = null;

  public LogOffDutyHolder ()
  {
  }

  public LogOffDutyHolder (DsLogAdmin.LogOffDuty initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DsLogAdmin.LogOffDutyHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DsLogAdmin.LogOffDutyHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DsLogAdmin.LogOffDutyHelper.type ();
  }

}
