package DsLogAdmin;

/**
* DsLogAdmin/LogRecordHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsLogAdmin.idl
* Thursday, February 1, 2018 2:55:16 PM BDT
*/

public final class LogRecordHolder implements org.omg.CORBA.portable.Streamable
{
  public DsLogAdmin.LogRecord value = null;

  public LogRecordHolder ()
  {
  }

  public LogRecordHolder (DsLogAdmin.LogRecord initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DsLogAdmin.LogRecordHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DsLogAdmin.LogRecordHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DsLogAdmin.LogRecordHelper.type ();
  }

}
