package DsLogAdmin;


/**
* DsLogAdmin/LogRecord.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsLogAdmin.idl
* Thursday, February 1, 2018 2:55:16 PM BDT
*/

public final class LogRecord implements org.omg.CORBA.portable.IDLEntity
{
  public long id = (long)0;
  public long time = (long)0;
  public DsLogAdmin.NVPair attr_list[] = null;

  // attributes, optional
  public org.omg.CORBA.Any info = null;

  public LogRecord ()
  {
  } // ctor

  public LogRecord (long _id, long _time, DsLogAdmin.NVPair[] _attr_list, org.omg.CORBA.Any _info)
  {
    id = _id;
    time = _time;
    attr_list = _attr_list;
    info = _info;
  } // ctor

} // class LogRecord
