package DsLogAdmin;


/**
* DsLogAdmin/OperationalState.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsLogAdmin.idl
* Thursday, February 1, 2018 2:55:17 PM BDT
*/

public class OperationalState implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static DsLogAdmin.OperationalState[] __array = new DsLogAdmin.OperationalState [__size];

  public static final int _disabled = 0;
  public static final DsLogAdmin.OperationalState disabled = new DsLogAdmin.OperationalState(_disabled);
  public static final int _enabled = 1;
  public static final DsLogAdmin.OperationalState enabled = new DsLogAdmin.OperationalState(_enabled);

  public int value ()
  {
    return __value;
  }

  public static DsLogAdmin.OperationalState from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected OperationalState (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class OperationalState
