package DsLogAdmin;


/**
* DsLogAdmin/QoSListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsLogAdmin.idl
* Thursday, February 1, 2018 2:55:17 PM BDT
*/

public final class QoSListHolder implements org.omg.CORBA.portable.Streamable
{
  public short value[] = null;

  public QoSListHolder ()
  {
  }

  public QoSListHolder (short[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DsLogAdmin.QoSListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DsLogAdmin.QoSListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DsLogAdmin.QoSListHelper.type ();
  }

}
