package DsLogAdmin;


/**
* DsLogAdmin/RecordIdListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsLogAdmin.idl
* Thursday, February 1, 2018 2:55:16 PM BDT
*/

public final class RecordIdListHolder implements org.omg.CORBA.portable.Streamable
{
  public long value[] = null;

  public RecordIdListHolder ()
  {
  }

  public RecordIdListHolder (long[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DsLogAdmin.RecordIdListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DsLogAdmin.RecordIdListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DsLogAdmin.RecordIdListHelper.type ();
  }

}
