package DsLogAdmin;


/**
* DsLogAdmin/RecordListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsLogAdmin.idl
* Thursday, February 1, 2018 2:55:16 PM BDT
*/

public final class RecordListHolder implements org.omg.CORBA.portable.Streamable
{
  public DsLogAdmin.LogRecord value[] = null;

  public RecordListHolder ()
  {
  }

  public RecordListHolder (DsLogAdmin.LogRecord[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DsLogAdmin.RecordListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DsLogAdmin.RecordListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DsLogAdmin.RecordListHelper.type ();
  }

}
