package DsLogAdmin;

/**
* DsLogAdmin/Time24IntervalHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsLogAdmin.idl
* Thursday, February 1, 2018 2:55:16 PM BDT
*/

public final class Time24IntervalHolder implements org.omg.CORBA.portable.Streamable
{
  public DsLogAdmin.Time24Interval value = null;

  public Time24IntervalHolder ()
  {
  }

  public Time24IntervalHolder (DsLogAdmin.Time24Interval initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DsLogAdmin.Time24IntervalHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DsLogAdmin.Time24IntervalHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DsLogAdmin.Time24IntervalHelper.type ();
  }

}
