package DsLogAdmin;


/**
* DsLogAdmin/TimeInterval.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsLogAdmin.idl
* Thursday, February 1, 2018 2:55:16 PM BDT
*/

public final class TimeInterval implements org.omg.CORBA.portable.IDLEntity
{
  public long start = (long)0;
  public long stop = (long)0;

  public TimeInterval ()
  {
  } // ctor

  public TimeInterval (long _start, long _stop)
  {
    start = _start;
    stop = _stop;
  } // ctor

} // class TimeInterval
