package DsLogAdmin;


/**
* DsLogAdmin/Time24Interval.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsLogAdmin.idl
* Thursday, February 1, 2018 2:55:17 PM BDT
*/

public final class Time24Interval implements org.omg.CORBA.portable.IDLEntity
{
  public DsLogAdmin.Time24 start = null;
  public DsLogAdmin.Time24 stop = null;

  public Time24Interval ()
  {
  } // ctor

  public Time24Interval (DsLogAdmin.Time24 _start, DsLogAdmin.Time24 _stop)
  {
    start = _start;
    stop = _stop;
  } // ctor

} // class Time24Interval
