package DsLogAdmin;

/**
* DsLogAdmin/WeekMaskItemHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsLogAdmin.idl
* Thursday, February 1, 2018 2:55:17 PM BDT
*/

public final class WeekMaskItemHolder implements org.omg.CORBA.portable.Streamable
{
  public DsLogAdmin.WeekMaskItem value = null;

  public WeekMaskItemHolder ()
  {
  }

  public WeekMaskItemHolder (DsLogAdmin.WeekMaskItem initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DsLogAdmin.WeekMaskItemHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DsLogAdmin.WeekMaskItemHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DsLogAdmin.WeekMaskItemHelper.type ();
  }

}
