package DsLogAdmin;


/**
* DsLogAdmin/WeekMaskItem.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from E:/projects/Corba/IDL/DsLogAdmin.idl
* Thursday, February 1, 2018 2:55:17 PM BDT
*/

public final class WeekMaskItem implements org.omg.CORBA.portable.IDLEntity
{
  public short days = (short)0;
  public DsLogAdmin.Time24Interval intervals[] = null;

  public WeekMaskItem ()
  {
  } // ctor

  public WeekMaskItem (short _days, DsLogAdmin.Time24Interval[] _intervals)
  {
    days = _days;
    intervals = _intervals;
  } // ctor

} // class WeekMaskItem
